// Auto-generated from IDX allCompanies.json — DO NOT EDIT MANUALLY
// Total: 957 emiten
export interface IdxEmiten {
  code: string;
  name: string;
  sector: string;
}
export const IDX_EMITEN: IdxEmiten[] = [
  { code: "AADI", name: "PT Adaro Andalan Indonesia Tbk", sector: "Batu Bara" },
  { code: "AALI", name: "Astra Agro Lestari Tbk", sector: "Produk Makanan Pertanian" },
  { code: "ABBA", name: "Mahaka Media Tbk", sector: "Media" },
  { code: "ABDA", name: "Asuransi Bina Dana Arta Tbk", sector: "Asuransi" },
  { code: "ABMM", name: "ABM Investama Tbk", sector: "Batu Bara" },
  { code: "ACES", name: "PT Aspirasi Hidup Indonesia Tbk", sector: "Ritel Khusus" },
  { code: "ACRO", name: "PT Samcro Hyosung Adilestari Tbk.", sector: "Pakaian & Barang Mewah" },
  { code: "ACST", name: "PT Acset Indonusa Tbk.", sector: "Konstruksi Bangunan" },
  {
    code: "ADCP",
    name: "PT Adhi Commuter Properti Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "ADES", name: "Akasha Wira International Tbk  Tbk", sector: "Minuman" },
  { code: "ADHI", name: "PT Adhi Karya (Persero) Tbk.", sector: "Konstruksi Bangunan" },
  { code: "ADMF", name: "Adira Dinamika Multi Finance Tbk", sector: "Pembiayaan Konsumen" },
  { code: "ADMG", name: "Polychem Indonesia Tbk", sector: "Barang Kimia" },
  { code: "ADMR", name: "PT Alamtri Minerals Indonesia Tbk", sector: "Batu Bara" },
  { code: "ADRO", name: "Alamtri Resources Indonesia Tbk", sector: "Batu Bara" },
  { code: "AEGS", name: "PT Anugerah Spareparts Sejahtera Tbk.", sector: "Komponen Otomotif" },
  { code: "AGAR", name: "PT Asia Sejahtera Mina Tbk", sector: "Produk Makanan Pertanian" },
  { code: "AGII", name: "PT Samator Indo Gas Tbk", sector: "Barang Kimia" },
  { code: "AGRO", name: "PT Bank Raya Indonesia Tbk", sector: "Bank" },
  { code: "AGRS", name: "PT Bank IBK Indonesia Tbk.", sector: "Bank" },
  { code: "AHAP", name: "Asuransi Harta Aman Pratama Tbk", sector: "Asuransi" },
  { code: "AIMS", name: "PT Artha Mahiya Investama Tbk", sector: "Batu Bara" },
  { code: "AISA", name: "PT FKS Food Sejahtera Tbk", sector: "Makanan Olahan" },
  { code: "AKKU", name: "PT Anugerah Kagum Karya Utama Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "AKPI", name: "Argha Karya Prima Ind. Tbk", sector: "Barang Kimia" },
  { code: "AKRA", name: "PT AKR Corporindo Tbk.", sector: "Minyak & Gas" },
  { code: "AKSI", name: "PT Mineral Sumberdaya Mandiri Tbk", sector: "Logistik & Pengantaran" },
  { code: "ALDO", name: "Alkindo Naratama Tbk", sector: "Wadah & Kemasan" },
  { code: "ALII", name: "PT Ancara Logistics Indonesia Tbk", sector: "Batu Bara" },
  { code: "ALKA", name: "Alakasa Industrindo Tbk", sector: "Logam & Mineral" },
  { code: "ALMI", name: "Alumindo Light Metal Industry Tbk", sector: "Logam & Mineral" },
  { code: "ALTO", name: "Tri Banyan Tirta Tbk", sector: "Minuman" },
  { code: "AMAG", name: "Asuransi Multi Artha Guna Tbk", sector: "Asuransi" },
  {
    code: "AMAN",
    name: "PT Makmur Berkah Amanda Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "AMAR", name: "PT Bank Amar Indonesia Tbk.", sector: "Bank" },
  { code: "AMFG", name: "Asahimas Flat Glass Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "AMIN", name: "PT Ateliers Mecaniques D Indonesie Tbk.", sector: "Mesin" },
  { code: "AMMN", name: "PT Amman Mineral Internasional Tbk.", sector: "Logam & Mineral" },
  { code: "AMMS", name: "PT Agung Menjangan Mas Tbk", sector: "Produk Makanan Pertanian" },
  { code: "AMOR", name: "PT Ashmore Asset Management Indonesia Tbk.", sector: "Jasa Investasi" },
  {
    code: "AMRT",
    name: "PT Sumber Alfaria Trijaya Tbk.",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "ANDI", name: "PT Andira Agro Tbk", sector: "Produk Makanan Pertanian" },
  { code: "ANJT", name: "PT Austindo Nusantara Jaya Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "ANTM", name: "Aneka Tambang Tbk.", sector: "Logam & Mineral" },
  { code: "APEX", name: "Apexindo Pratama Duta Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  {
    code: "APIC",
    name: "PACIFIC STRATEGIC FINANCIAL Tbk",
    sector: "Perusahaan Holding & Investasi",
  },
  { code: "APII", name: "PT Arita Prima Indonesia Tbk.", sector: "Mesin" },
  { code: "APLI", name: "Asiaplast Industries Tbk", sector: "Barang Kimia" },
  {
    code: "APLN",
    name: "PT Agung Podomoro Land Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "ARCI", name: "PT Archi Indonesia Tbk", sector: "Logam & Mineral" },
  { code: "AREA", name: "PT Dunia Virtual Online Tbk", sector: "Jasa & Konsultan TI" },
  { code: "ARGO", name: "Argo Pantes Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "ARII", name: "Atlas Resources Tbk", sector: "Batu Bara" },
  { code: "ARKA", name: "PT Arkha Jayanti Persada Tbk.", sector: "Mesin" },
  { code: "ARKO", name: "PT Arkora Hydro Tbk.", sector: "Utilitas Listrik" },
  { code: "ARMY", name: "PT Armidian Karyatama Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "ARNA", name: "Arwana Citramulia Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "ARTA", name: "Arthavest Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "ARTI", name: "Ratu Prabu Energi Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "ARTO", name: "PT Bank Jago Tbk.", sector: "Bank" },
  { code: "ASBI", name: "Asuransi Bintang Tbk", sector: "Asuransi" },
  { code: "ASDM", name: "Asuransi Dayin Mitra Tbk", sector: "Asuransi" },
  { code: "ASGR", name: "Astra Graphia Tbk", sector: "Jasa Komersial" },
  {
    code: "ASHA",
    name: "PT Cilacap Samudera Fishing Industry Tbk",
    sector: "Produk Makanan Pertanian",
  },
  { code: "ASII", name: "Astra International Tbk", sector: "Perusahaan Holding Multi-sektor" },
  { code: "ASJT", name: "Asuransi Jasa Tania Tbk", sector: "Asuransi" },
  { code: "ASLC", name: "PT Autopedia Sukses Lestari Tbk", sector: "Ritel Khusus" },
  { code: "ASLI", name: "PT Asri Karya Lestari Tbk.", sector: "Konstruksi Bangunan" },
  { code: "ASMI", name: "PT Asuransi Maximus Graha Persada Tbk.", sector: "Asuransi" },
  {
    code: "ASPI",
    name: "PT Andalan Sakti Primaindo Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "ASPR", name: "PT Asia Pramulia Tbk", sector: "Wadah & Kemasan" },
  { code: "ASRI", name: "ALAM SUTERA REALTY Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "ASRM", name: "Asuransi Ramayana Tbk", sector: "Asuransi" },
  { code: "ASSA", name: "Adi Sarana Armada Tbk", sector: "Pengangkutan Darat Penumpang" },
  {
    code: "ATAP",
    name: "PT Trimitra Prawara Goldland Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "ATIC", name: "PT Anabatic Technologies Tbk", sector: "Jasa & Konsultan TI" },
  {
    code: "ATLA",
    name: "PT Atlantis Subsea Indonesia Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "AUTO", name: "Astra Otoparts Tbk", sector: "Komponen Otomotif" },
  { code: "AVIA", name: "PT Avia Avian Tbk", sector: "Barang Kimia" },
  { code: "AWAN", name: "PT Era Digital Media Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "AXIO", name: "PT Tera Data Indonusa Tbk", sector: "Perangkat Komputer" },
  { code: "AYAM", name: "PT Janu Putra Sejahtera Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "AYLS", name: "PT Agro Yasa Lestari Tbk", sector: "Material Konstruksi" },
  { code: "BABP", name: "PT Bank MNC Internasional Tbk.", sector: "Bank" },
  { code: "BABY", name: "PT Multitrend Indo Tbk.", sector: "Ritel Khusus" },
  { code: "BACA", name: "PT Bank Capital Indonesia Tbk", sector: "Bank" },
  { code: "BAIK", name: "PT Bersama Mencapai Puncak Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "BAJA", name: "Saranacentral Bajatama Tbk", sector: "Logam & Mineral" },
  { code: "BALI", name: "PT Bali Towerindo Sentra Tbk.", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "BANK", name: "PT Bank Aladin Syariah Tbk", sector: "Bank" },
  { code: "BAPA", name: "Bekasi Asri Pemula Tbk", sector: "Pengelola & Pengembang Real Estat" },
  {
    code: "BAPI",
    name: "PT Bhakti Agung Propertindo Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "BATA", name: "Sepatu Bata Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "BATR", name: "PT Benteng Api Technic Tbk", sector: "Material Konstruksi" },
  { code: "BAUT", name: "PT Mitra Angkasa Sejahtera Tbk", sector: "Ritel Khusus" },
  { code: "BAYU", name: "Bayu Buana Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "BBCA", name: "PT Bank Central Asia Tbk.", sector: "Bank" },
  { code: "BBHI", name: "PT Allo Bank Indonesia Tbk", sector: "Bank" },
  { code: "BBKP", name: "PT Bank KB Indonesia Tbk", sector: "Bank" },
  { code: "BBLD", name: "Buana Finance Tbk", sector: "Pembiayaan Konsumen" },
  { code: "BBMD", name: "PT Bank Mestika Dharma Tbk.", sector: "Bank" },
  { code: "BBNI", name: "PT Bank Negara Indonesia (Persero) Tbk", sector: "Bank" },
  { code: "BBRI", name: "PT Bank Rakyat Indonesia (Persero) Tbk", sector: "Bank" },
  { code: "BBRM", name: "Pelayaran Nasional Bina Buana Raya Tbk", sector: "Batu Bara" },
  { code: "BBSI", name: "PT Krom Bank Indonesia Tbk", sector: "Bank" },
  {
    code: "BBSS",
    name: "PT Bumi Benowo Sukses Sejahtera Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "BBTN", name: "PT Bank Tabungan Negara (Persero) Tbk", sector: "Bank" },
  { code: "BBYB", name: "PT Bank Neo Commerce Tbk.", sector: "Bank" },
  { code: "BCAP", name: "MNC Kapital Indonesia Tbk", sector: "Perusahaan Holding & Investasi" },
  { code: "BCIC", name: "PT Bank JTrust Indonesia Tbk.", sector: "Bank" },
  { code: "BCIP", name: "Bumi Citra Permai Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "BDKR", name: "PT Berdikari Pondasi Perkasa Tbk.", sector: "Konstruksi Bangunan" },
  { code: "BDMN", name: "PT Bank Danamon Indonesia Tbk", sector: "Bank" },
  { code: "BEBS", name: "PT Berkah Beton Sadaya Tbk", sector: "Material Konstruksi" },
  { code: "BEEF", name: "PT Estika Tata Tiara Tbk.", sector: "Makanan Olahan" },
  { code: "BEER", name: "PT Jobubu Jarum Minahasa Tbk", sector: "Minuman" },
  { code: "BEKS", name: "PT Bank Pembangunan Daerah Banten Tbk.", sector: "Bank" },
  { code: "BELI", name: "PT Global Digital Niaga Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "BELL", name: "PT Trisula Textile Industries Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "BESS", name: "PT Batulicin Nusantara Maritim Tbk.", sector: "Batu Bara" },
  {
    code: "BEST",
    name: "Bekasi Fajar Industrial Estate Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "BFIN", name: "BFI Finance Indonesia Tbk", sector: "Pembiayaan Konsumen" },
  { code: "BGTG", name: "PT Bank Ganesha Tbk.", sector: "Bank" },
  { code: "BHAT", name: "PT Bhakti Multi Artha Tbk.", sector: "Asuransi" },
  { code: "BHIT", name: "PT MNC Asia Holding Tbk", sector: "Perusahaan Holding Multi-sektor" },
  {
    code: "BIKA",
    name: "PT Binakarya Jaya Abadi Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  {
    code: "BIKE",
    name: "PT Sepeda Bersama Indonesia Tbk",
    sector: "Peralatan Olah Raga & Barang Hobi",
  },
  { code: "BIMA", name: "Primarindo Asia Infrastructure Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "BINA", name: "PT Bank Ina Perdana Tbk.", sector: "Bank" },
  { code: "BINO", name: "PT Perma Plasindo Tbk", sector: "Jasa Komersial" },
  { code: "BIPI", name: "PT Astrindo Nusantara Infrastruktur Tbk.", sector: "Batu Bara" },
  {
    code: "BIPP",
    name: "Bhuwanatala Indah Permai Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "BIRD", name: "PT Blue Bird Tbk", sector: "Pengangkutan Darat Penumpang" },
  { code: "BISI", name: "BISI INTERNATIONAL Tbk", sector: "Produk Makanan Pertanian" },
  { code: "BJBR", name: "Bank Pembangunan Daerah Jawa Barat dan Banten Tbk", sector: "Bank" },
  { code: "BJTM", name: "Bank Pembangunan Daerah Jawa Timur Tbk", sector: "Bank" },
  { code: "BKDP", name: "Bukit Darmo Property Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "BKSL", name: "Sentul City Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "BKSW", name: "PT Bank QNB Indonesia Tbk", sector: "Bank" },
  { code: "BLES", name: "PT Superior Prima Sukses Tbk", sector: "Material Konstruksi" },
  { code: "BLOG", name: "PT Trimitra Trans Persada Tbk", sector: "Logistik & Pengantaran" },
  { code: "BLTA", name: "Berlian Laju Tanker Tbk", sector: "Logistik & Pengantaran" },
  { code: "BLTZ", name: "PT Graha Layar Prima Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "BLUE", name: "PT Berkah Prima Perkasa Tbk", sector: "Jasa Komersial" },
  { code: "BMAS", name: "PT Bank Maspion Indonesia Tbk.", sector: "Bank" },
  { code: "BMBL", name: "PT Lavender Bina Cendikia Tbk", sector: "Pendidikan & Jasa Penunjang" },
  { code: "BMHS", name: "PT Bundamedik Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "BMRI", name: "PT Bank Mandiri (Persero) Tbk", sector: "Bank" },
  { code: "BMSR", name: "Bintang Mitra Semestaraya Tbk", sector: "Barang Kimia" },
  { code: "BMTR", name: "PT Global Mediacom Tbk", sector: "Media" },
  { code: "BNBA", name: "Bank Bumi Arta Tbk", sector: "Bank" },
  { code: "BNBR", name: "Bakrie & Brothers Tbk", sector: "Perusahaan Holding Multi-sektor" },
  { code: "BNGA", name: "PT Bank CIMB Niaga Tbk", sector: "Bank" },
  { code: "BNII", name: "PT Bank Maybank Indonesia Tbk", sector: "Bank" },
  { code: "BNLI", name: "Bank Permata Tbk", sector: "Bank" },
  {
    code: "BOAT",
    name: "PT Newport Marine Services Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "BOBA", name: "PT Formosa Ingredient Factory Tbk", sector: "Makanan Olahan" },
  { code: "BOGA", name: "PT Bintang Oto Global Tbk", sector: "Ritel Khusus" },
  { code: "BOLA", name: "PT Bali Bintang Sejahtera Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "BOLT", name: "PT Garuda Metalindo Tbk.", sector: "Komponen Otomotif" },
  { code: "BOSS", name: "PT Borneo Olah Sarana Sukses Tbk.", sector: "Batu Bara" },
  { code: "BPFI", name: "PT Woori Finance Indonesia Tbk", sector: "Pembiayaan Konsumen" },
  {
    code: "BPII",
    name: "PT Batavia Prosperindo Internasional Tbk.",
    sector: "Perusahaan Holding & Investasi",
  },
  {
    code: "BPTR",
    name: "PT Batavia Prosperindo Trans Tbk.",
    sector: "Pengangkutan Darat Penumpang",
  },
  { code: "BRAM", name: "Indo Kordsa Tbk", sector: "Komponen Otomotif" },
  { code: "BREN", name: "PT Barito Renewables Energy Tbk.", sector: "Utilitas Listrik" },
  { code: "BRIS", name: "PT Bank Syariah Indonesia Tbk", sector: "Bank" },
  { code: "BRMS", name: "Bumi Resources Minerals Tbk", sector: "Logam & Mineral" },
  { code: "BRNA", name: "Berlina Tbk", sector: "Wadah & Kemasan" },
  { code: "BRPT", name: "Barito Pacific Tbk", sector: "Barang Kimia" },
  { code: "BRRC", name: "PT Raja Roti Cemerlang Tbk", sector: "Makanan Olahan" },
  {
    code: "BSBK",
    name: "PT Wulandari Bangun Laksana Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "BSDE", name: "PT Bumi Serpong Damai Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "BSIM", name: "Bank Sinarmas Tbk", sector: "Bank" },
  { code: "BSML", name: "PT Bintang Samudera Mandiri Lines Tbk", sector: "Batu Bara" },
  { code: "BSSR", name: "Baramulti Suksessarana Tbk", sector: "Batu Bara" },
  { code: "BSWD", name: "Bank of India Indonesia Tbk", sector: "Bank" },
  { code: "BTEK", name: "Bumi Teknokultura Unggul Tbk", sector: "Produk Makanan Pertanian" },
  { code: "BTEL", name: "Bakrie Telecom Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "BTON", name: "Betonjaya Manunggal Tbk", sector: "Logam & Mineral" },
  { code: "BTPN", name: "PT Bank SMBC Indonesia Tbk", sector: "Bank" },
  { code: "BTPS", name: "PT Bank BTPN Syariah Tbk.", sector: "Bank" },
  {
    code: "BUAH",
    name: "PT Segar Kumala Indonesia Tbk",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "BUDI", name: "PT Budi Starch & Sweetener Tbk.", sector: "Makanan Olahan" },
  { code: "BUKA", name: "PT Bukalapak.com Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "BUKK", name: "Bukaka Teknik Utama Tbk", sector: "Konstruksi Bangunan" },
  { code: "BULL", name: "PT Buana Lintas Lautan Tbk.", sector: "Minyak & Gas" },
  { code: "BUMI", name: "Bumi Resources Tbk", sector: "Batu Bara" },
  { code: "BUVA", name: "PT Bukit Uluwatu Villa Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "BVIC", name: "Bank Victoria International Tbk", sector: "Bank" },
  { code: "BWPT", name: "Eagle High Plantations Tbk", sector: "Produk Makanan Pertanian" },
  { code: "BYAN", name: "Bayan Resources Tbk", sector: "Batu Bara" },
  {
    code: "CAKK",
    name: "PT Cahayaputra Asa Keramik Tbk.",
    sector: "Produk & Perlengkapan Bangunan",
  },
  { code: "CAMP", name: "PT Campina Ice Cream Industry Tbk.", sector: "Makanan Olahan" },
  { code: "CANI", name: "PT Capitol Nusantara Indonesia Tbk.", sector: "Batu Bara" },
  { code: "CARE", name: "PT Metro Healthcare Indonesia Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "CARS", name: "PT Industri dan Perdagangan Bintraco Dharma Tbk", sector: "Ritel Khusus" },
  {
    code: "CASA",
    name: "PT Capital Financial Indonesia Tbk",
    sector: "Perusahaan Holding & Investasi",
  },
  { code: "CASH", name: "PT Cashlez Worldwide Indonesia Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "CASS", name: "Cahaya Aero Services Tbk", sector: "Operator Infrastruktur Transportasi" },
  {
    code: "CBDK",
    name: "PT Bangun Kosambi Sukses Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "CBMF", name: "PT Cahaya Bintang Medan Tbk", sector: "Barang Rumah Tangga" },
  { code: "CBPE", name: "PT Citra Buana Prasida Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "CBRE", name: "PT Cakra Buana Resources Energi Tbk", sector: "Batu Bara" },
  { code: "CBUT", name: "PT Citra Borneo Utama Tbk", sector: "Produk Makanan Pertanian" },
  { code: "CCSI", name: "PT Communication Cable Systems Indonesia Tbk.", sector: "Kelistrikan" },
  { code: "CDIA", name: "PT Chandra Daya Investasi Tbk", sector: "Utilitas Listrik" },
  { code: "CEKA", name: "PT Wilmar Cahaya Indonesia Tbk.", sector: "Makanan Olahan" },
  {
    code: "CENT",
    name: "PT Centratama Telekomunikasi Indonesia Tbk.",
    sector: "Jasa Telekomunikasi Nirkabel",
  },
  { code: "CFIN", name: "Clipan Finance Indonesia Tbk", sector: "Pembiayaan Konsumen" },
  { code: "CGAS", name: "PT Citra Nusantara Gemilang Tbk.", sector: "Minyak & Gas" },
  {
    code: "CHEK",
    name: "PT Diastika Biotekindo Tbk",
    sector: "Peralatan & Perlengkapan Kesehatan",
  },
  { code: "CHEM", name: "PT Chemstar Indonesia Tbk", sector: "Barang Kimia" },
  {
    code: "CHIP",
    name: "PT Pelita Teknologi Global Tbk",
    sector: "Perangkat, Instrumen & Komponen Elektronik",
  },
  { code: "CINT", name: "PT Chitose Internasional Tbk", sector: "Barang Rumah Tangga" },
  { code: "CITA", name: "Cita Mineral Investindo Tbk", sector: "Logam & Mineral" },
  {
    code: "CITY",
    name: "PT Natura City Developments Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "CLAY", name: "PT Citra Putra Realty Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "CLEO", name: "PT Sariguna Primatirta Tbk", sector: "Minuman" },
  { code: "CLPI", name: "Colorpak Indonesia Tbk", sector: "Barang Kimia" },
  {
    code: "CMNP",
    name: "Citra Marga Nusaphala Persada Tbk",
    sector: "Operator Infrastruktur Transportasi",
  },
  { code: "CMNT", name: "PT Cemindo Gemilang Tbk", sector: "Material Konstruksi" },
  { code: "CMPP", name: "PT AirAsia Indonesia Tbk", sector: "Maskapai Penerbangan" },
  { code: "CMRY", name: "PT Cisarua Mountain Dairy Tbk", sector: "Makanan Olahan" },
  { code: "CNKO", name: "Exploitasi Energi Indonesia Tbk", sector: "Batu Bara" },
  { code: "CNMA", name: "PT Nusantara Sejahtera Raya Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "CNTX", name: "PT Century Textile Industry Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "COAL", name: "PT Black Diamond Resources Tbk", sector: "Batu Bara" },
  { code: "COCO", name: "PT Wahana Interfood Nusantara Tbk.", sector: "Makanan Olahan" },
  {
    code: "COIN",
    name: "PT Indokripto Koin Semesta Tbk",
    sector: "Perusahaan Holding & Investasi",
  },
  { code: "COWL", name: "COWELL DEVELOPMENT Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "CPIN", name: "Charoen Pokphand Indonesia Tbk", sector: "Produk Makanan Pertanian" },
  {
    code: "CPRI",
    name: "PT Capri Nusa Satu Properti Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "CPRO", name: "Central Proteina Prima Tbk", sector: "Produk Makanan Pertanian" },
  { code: "CRAB", name: "PT Toba Surimi Industries Tbk", sector: "Produk Makanan Pertanian" },
  { code: "CRSN", name: "PT Carsurin Tbk", sector: "Jasa Profesional" },
  { code: "CSAP", name: "Catur Sentosa Adiprana Tbk", sector: "Ritel Khusus" },
  {
    code: "CSIS",
    name: "PT Cahayasakti Investindo Sukses Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "CSMI", name: "PT Cipta Selera Murni Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "CSRA", name: "PT Cisadane Sawit Raya Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "CTBN", name: "Citra Tubindo Tbk", sector: "Logam & Mineral" },
  { code: "CTRA", name: "Ciputra Development Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "CTTH", name: "Citatah Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "CUAN", name: "PT Petrindo Jaya Kreasi Tbk", sector: "Batu Bara" },
  { code: "CYBR", name: "PT ITSEC Asia Tbk.", sector: "Jasa & Konsultan TI" },
  { code: "DAAZ", name: "PT Daaz Bara Lestari Tbk", sector: "Logam & Mineral" },
  {
    code: "DADA",
    name: "PT Diamond Citra Propertindo Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "DART", name: "Duta Anggada Realty Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "DATA", name: "PT Remala Abadi Tbk", sector: "Jasa Telekomunikasi" },
  { code: "DAYA", name: "PT Duta Intidaya Tbk.", sector: "Perdagangan Ritel Barang Primer" },
  { code: "DCII", name: "PT DCI Indonesia Tbk", sector: "Jasa & Konsultan TI" },
  { code: "DEAL", name: "PT Dewata Freightinternational Tbk.", sector: "Logistik & Pengantaran" },
  { code: "DEFI", name: "Danasupra Erapacific Tbk", sector: "Perusahaan Holding & Investasi" },
  { code: "DEPO", name: "PT Caturkarda Depo Bangunan Tbk", sector: "Ritel Khusus" },
  { code: "DEWA", name: "Darma Henwa Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "DEWI", name: "PT Dewi Shri Farmindo Tbk", sector: "Produk Makanan Pertanian" },
  { code: "DFAM", name: "PT Dafam Property Indonesia Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "DGIK", name: "Nusa Konstruksi Enjiniring  Tbk", sector: "Konstruksi Bangunan" },
  { code: "DGNS", name: "PT Diagnos Laboratorium Utama Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "DGWG", name: "PT Delta Giri Wacana Tbk", sector: "Barang Kimia" },
  { code: "DIGI", name: "PT Arkadia Digital Media Tbk", sector: "Media" },
  { code: "DILD", name: "Intiland Development Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "DIVA", name: "PT Distribusi Voucher Nusantara Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "DKFT", name: "Central Omega Resources Tbk", sector: "Logam & Mineral" },
  { code: "DKHH", name: "PT Cipta Sarana Medika Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "DLTA", name: "Delta Djakarta Tbk", sector: "Minuman" },
  { code: "DMAS", name: "PT Puradelta Lestari Tbk.", sector: "Pengelola & Pengembang Real Estat" },
  { code: "DMMX", name: "PT Digital Mediatama Maxima Tbk", sector: "Jasa & Konsultan TI" },
  {
    code: "DMND",
    name: "PT Diamond Food Indonesia Tbk.",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "DNAR", name: "PT Bank Oke Indonesia Tbk.", sector: "Bank" },
  {
    code: "DNET",
    name: "PT Indoritel Makmur Internasional Tbk.",
    sector: "Perusahaan Holding & Investasi",
  },
  {
    code: "DOID",
    name: "PT BUMA Internasional Grup Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "DOOH", name: "PT Era Media Sejahtera Tbk", sector: "Media" },
  { code: "DOSS", name: "PT Global Sukses Digital Tbk", sector: "Barang Elektronik Konsumen" },
  { code: "DPNS", name: "Duta Pertiwi Nusantara Tbk", sector: "Barang Kimia" },
  { code: "DPUM", name: "PT Dua Putra Utama Makmur Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "DRMA", name: "PT Dharma Polimetal Tbk", sector: "Komponen Otomotif" },
  { code: "DSFI", name: "Dharma Samudera Fishing Ind. Tbk", sector: "Produk Makanan Pertanian" },
  { code: "DSNG", name: "PT Dharma Satya Nusantara Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "DSSA", name: "Dian Swastatika Sentosa Tbk", sector: "Batu Bara" },
  { code: "DUCK", name: "PT Jaya Bersama Indo Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "DUTI", name: "Duta Pertiwi Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "DVLA", name: "Darya-Varia Laboratoria Tbk", sector: "Farmasi" },
  { code: "DWGL", name: "PT Dwi Guna Laksana Tbk", sector: "Batu Bara" },
  { code: "DYAN", name: "PT Dyandra Media International Tbk.", sector: "Jasa Komersial" },
  { code: "EAST", name: "PT Eastparc Hotel Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "ECII", name: "PT Electronic City Indonesia Tbk.", sector: "Ritel Khusus" },
  { code: "EDGE", name: "PT Indointernet Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "EKAD", name: "Ekadharma International Tbk", sector: "Barang Kimia" },
  { code: "ELIT", name: "PT Data Sinergitama Jaya Tbk", sector: "Jasa & Konsultan TI" },
  {
    code: "ELPI",
    name: "PT Pelayaran Nasional Ekalya Purnamasari Tbk",
    sector: "Logistik & Pengantaran",
  },
  { code: "ELSA", name: "Elnusa Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "ELTY", name: "Bakrieland Development Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "EMAS", name: "PT Merdeka Gold Resources Tbk", sector: "Logam & Mineral" },
  {
    code: "EMDE",
    name: "Megapolitan Developments Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "EMTK", name: "Elang Mahkota Teknologi Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "ENAK", name: "PT Champ Resto Indonesia Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "ENRG", name: "Energi Mega Persada Tbk", sector: "Minyak & Gas" },
  { code: "ENVY", name: "PT Envy Technologies Indonesia Tbk", sector: "Jasa & Konsultan TI" },
  { code: "ENZO", name: "PT Morenzo Abadi Perkasa Tbk", sector: "Produk Makanan Pertanian" },
  { code: "EPAC", name: "PT Megalestari Epack Sentosaraya Tbk.", sector: "Wadah & Kemasan" },
  {
    code: "EPMT",
    name: "Enseval Putera Megatrading Tbk",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "ERAA", name: "Erajaya Swasembada Tbk", sector: "Ritel Khusus" },
  { code: "ERAL", name: "PT Sinar Eka Selaras Tbk", sector: "Ritel Khusus" },
  { code: "ERTX", name: "Eratex Djaja Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "ESIP", name: "PT Sinergi Inti Plastindo Tbk.", sector: "Wadah & Kemasan" },
  { code: "ESSA", name: "ESSA Industries Indonesia Tbk", sector: "Barang Kimia" },
  { code: "ESTA", name: "PT Esta Multi Usaha Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "ESTI", name: "Ever Shine Textile Industry Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "ETWA", name: "Eterindo Wahanatama Tbk", sector: "Barang Kimia" },
  { code: "EURO", name: "PT Estee Gold Feet Tbk", sector: "Produk Perawatan Tubuh" },
  {
    code: "EXCL",
    name: "PT XLSMART Telecom Sejahtera Tbk",
    sector: "Jasa Telekomunikasi Nirkabel",
  },
  { code: "FAPA", name: "PT FAP Agri Tbk", sector: "Produk Makanan Pertanian" },
  { code: "FAST", name: "PT Fast Food Indonesia Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "FASW", name: "Fajar Surya Wisesa Tbk", sector: "Wadah & Kemasan" },
  { code: "FILM", name: "PT MD Entertainment Tbk", sector: "Hiburan & Film" },
  { code: "FIMP", name: "PT Fimperkasa Utama Tbk", sector: "Konstruksi Bangunan" },
  { code: "FIRE", name: "PT Alfa Energi Investama Tbk.", sector: "Batu Bara" },
  { code: "FISH", name: "FKS Multi Agro Tbk", sector: "Produk Makanan Pertanian" },
  { code: "FITT", name: "PT Hotel Fitra International Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "FLMC", name: "PT Falmaco Nonwoven Industri Tbk", sector: "Produk Perawatan Tubuh" },
  { code: "FMII", name: "Fortune Mate Indonesia Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "FOLK", name: "PT Multi Garam Utama Tbk.", sector: "Perusahaan Holding Multi-sektor" },
  { code: "FOOD", name: "PT Sentra Food Indonesia Tbk.", sector: "Makanan Olahan" },
  { code: "FORE", name: "PT Fore Kopi Indonesia Tbk", sector: "Minuman" },
  { code: "FORU", name: "Fortune Indonesia Tbk", sector: "Media" },
  { code: "FPNI", name: "PT Lotte Chemical Titan Tbk.", sector: "Barang Kimia" },
  { code: "FUJI", name: "PT Fuji Finance Indonesia Tbk.", sector: "Pembiayaan Konsumen" },
  { code: "FUTR", name: "PT Futura Energi Global Tbk", sector: "Media" },
  { code: "FWCT", name: "PT Wijaya Cahaya Timber Tbk", sector: "Perhutanan & Kertas" },
  {
    code: "GAMA",
    name: "Aksara Global Development Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "GDST", name: "Gunawan Dianjaya Steel Tbk", sector: "Logam & Mineral" },
  { code: "GDYR", name: "Goodyear Indonesia Tbk", sector: "Komponen Otomotif" },
  { code: "GEMA", name: "Gema Grahasarana Tbk", sector: "Barang Rumah Tangga" },
  { code: "GEMS", name: "Golden Energy Mines Tbk", sector: "Batu Bara" },
  { code: "GGRM", name: "Gudang Garam Tbk", sector: "Rokok" },
  { code: "GGRP", name: "PT Gunung Raja Paksi Tbk.", sector: "Logam & Mineral" },
  {
    code: "GHON",
    name: "PT Gihon Telekomunikasi Indonesia Tbk",
    sector: "Jasa Telekomunikasi Nirkabel",
  },
  { code: "GIAA", name: "Garuda Indonesia (Persero) Tbk", sector: "Maskapai Penerbangan" },
  { code: "GJTL", name: "Gajah Tunggal Tbk", sector: "Komponen Otomotif" },
  { code: "GLOB", name: "PT Globe Kita Terang Tbk", sector: "Ritel Khusus" },
  {
    code: "GLVA",
    name: "PT Galva Technologies Tbk",
    sector: "Perangkat, Instrumen & Komponen Elektronik",
  },
  {
    code: "GMFI",
    name: "PT Garuda Maintenance Facility Aero Asia Tbk.",
    sector: "Operator Infrastruktur Transportasi",
  },
  {
    code: "GMTD",
    name: "Gowa Makassar Tourism Development Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  {
    code: "GOLD",
    name: "PT Visi Telekomunikasi Infrastruktur Tbk.",
    sector: "Jasa Telekomunikasi Nirkabel",
  },
  { code: "GOLF", name: "PT Intra GolfLink Resorts Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "GOLL", name: "PT Golden Plantation Tbk", sector: "Produk Makanan Pertanian" },
  { code: "GOOD", name: "PT Garudafood Putra Putri Jaya Tbk.", sector: "Makanan Olahan" },
  { code: "GOTO", name: "PT GoTo Gojek Tokopedia Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "GPRA", name: "Perdana Gapura Prima Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "GPSO", name: "PT Geoprima Solusi Tbk", sector: "Mesin" },
  {
    code: "GRIA",
    name: "PT Ingria Pratama Capitalindo Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "GRPH", name: "PT Griptha Putra Persada Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "GRPM", name: "PT Graha Prima Mentari Tbk.", sector: "Minuman" },
  {
    code: "GSMF",
    name: "Equity Development Investment Tbk",
    sector: "Perusahaan Holding & Investasi",
  },
  { code: "GTBO", name: "Garda Tujuh Buana Tbk", sector: "Batu Bara" },
  { code: "GTRA", name: "PT Grahaprima Suksesmandiri Tbk", sector: "Logistik & Pengantaran" },
  { code: "GTSI", name: "PT GTS Internasional Tbk", sector: "Minyak & Gas" },
  { code: "GULA", name: "PT Aman Agrindo Tbk", sector: "Makanan Olahan" },
  { code: "GUNA", name: "PT Gunanusa Eramandiri Tbk", sector: "Produk Makanan Pertanian" },
  { code: "GWSA", name: "PT Greenwood Sejahtera Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "GZCO", name: "Gozco Plantations Tbk", sector: "Produk Makanan Pertanian" },
  { code: "HADE", name: "PT Himalaya Energi Perkasa Tbk", sector: "Utilitas Gas" },
  { code: "HAIS", name: "PT Hasnur Internasional Shipping Tbk", sector: "Logistik & Pengantaran" },
  { code: "HAJJ", name: "PT Arsy Buana Travelindo Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "HALO", name: "PT Haloni Jane Tbk", sector: "Peralatan & Perlengkapan Kesehatan" },
  { code: "HATM", name: "PT Habco Trans Maritima Tbk", sector: "Logistik & Pengantaran" },
  {
    code: "HBAT",
    name: "PT Minahasa Membangun Hebat Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "HDFA", name: "Radana Bhaskara Finance Tbk", sector: "Pembiayaan Konsumen" },
  { code: "HDIT", name: "PT Hensel Davest Indonesia Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "HEAL", name: "PT Medikaloka Hermina Tbk.", sector: "Penyedia Jasa Kesehatan" },
  { code: "HELI", name: "PT Jaya Trishindo Tbk", sector: "Maskapai Penerbangan" },
  { code: "HERO", name: "PT DFI Retail Nusantara Tbk", sector: "Perdagangan Ritel Barang Primer" },
  { code: "HEXA", name: "Hexindo Adiperkasa Tbk", sector: "Mesin" },
  { code: "HGII", name: "PT Hero Global Investment Tbk", sector: "Utilitas Listrik" },
  { code: "HILL", name: "PT Hillcon Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "HITS", name: "Humpuss Intermoda Transportasi Tbk", sector: "Minyak & Gas" },
  { code: "HKMU", name: "PT HK Metals Utama Tbk", sector: "Logam & Mineral" },
  { code: "HMSP", name: "HM Sampoerna Tbk", sector: "Rokok" },
  { code: "HOKI", name: "PT Buyung Poetra Sembada Tbk.", sector: "Makanan Olahan" },
  { code: "HOME", name: "Hotel Mandarine Regency Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "HOMI", name: "PT Grand House Mulia Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "HOPE", name: "PT Harapan Duta Pertiwi Tbk.", sector: "Mesin" },
  { code: "HOTL", name: "Saraswati Griya Lestari Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "HRME", name: "PT Menteng Heritage Realty Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "HRTA", name: "PT Hartadinata Abadi Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "HRUM", name: "Harum Energy Tbk", sector: "Batu Bara" },
  { code: "HUMI", name: "PT Humpuss Maritim Internasional Tbk", sector: "Minyak & Gas" },
  { code: "HYGN", name: "PT Ecocare Indo Pasifik Tbk.", sector: "Jasa Komersial" },
  { code: "IATA", name: "PT MNC Energy Investments Tbk", sector: "Batu Bara" },
  { code: "IBFN", name: "PT Intan Baru Prana Tbk", sector: "Mesin" },
  { code: "IBOS", name: "PT Indo Boga Sukses Tbk", sector: "Makanan Olahan" },
  { code: "IBST", name: "Inti Bangun Sejahtera Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "ICBP", name: "Indofood CBP Sukses Makmur Tbk", sector: "Makanan Olahan" },
  { code: "ICON", name: "Island Concepts Indonesia Tbk", sector: "Jasa Komersial" },
  { code: "IDEA", name: "PT Idea Indonesia Akademi Tbk", sector: "Pendidikan & Jasa Penunjang" },
  { code: "IDPR", name: "PT Indonesia Pondasi Raya Tbk.", sector: "Konstruksi Bangunan" },
  { code: "IFII", name: "PT Indonesia Fibreboard Industry Tbk", sector: "Perhutanan & Kertas" },
  { code: "IFSH", name: "PT Ifishdeco Tbk.", sector: "Logam & Mineral" },
  { code: "IGAR", name: "Champion Pacific Indonesia Tbk", sector: "Wadah & Kemasan" },
  { code: "IIKP", name: "Inti Agri Resources Tbk", sector: "Peralatan Olah Raga & Barang Hobi" },
  {
    code: "IKAI",
    name: "Intikeramik Alamasri Industri Tbk",
    sector: "Produk & Perlengkapan Bangunan",
  },
  { code: "IKAN", name: "PT Era Mandiri Cemerlang Tbk", sector: "Produk Makanan Pertanian" },
  { code: "IKBI", name: "Sumi Indo Kabel Tbk", sector: "Kelistrikan" },
  { code: "IKPM", name: "PT Ikapharmindo Putramas Tbk.", sector: "Farmasi" },
  { code: "IMAS", name: "Indomobil Sukses Internasional Tbk", sector: "Ritel Khusus" },
  { code: "IMJS", name: "PT Indomobil Multi Jasa Tbk.", sector: "Pengangkutan Darat Penumpang" },
  {
    code: "IMPC",
    name: "PT Impack Pratama Industri Tbk",
    sector: "Produk & Perlengkapan Bangunan",
  },
  { code: "INAF", name: "Indofarma Tbk.", sector: "Farmasi" },
  { code: "INAI", name: "Indal Aluminium Industry Tbk", sector: "Logam & Mineral" },
  { code: "INCF", name: "PT Indo Komoditi Korpora Tbk", sector: "Perhutanan & Kertas" },
  { code: "INCI", name: "Intanwijaya Internasional Tbk", sector: "Barang Kimia" },
  { code: "INCO", name: "Vale Indonesia Tbk", sector: "Logam & Mineral" },
  { code: "INDF", name: "Indofood Sukses Makmur Tbk", sector: "Makanan Olahan" },
  {
    code: "INDO",
    name: "PT Royalindo Investa Wijaya Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "INDR", name: "PT Indo-Rama Synthetics Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "INDS", name: "Indospring Tbk", sector: "Komponen Otomotif" },
  { code: "INDX", name: "Tanah Laut Tbk", sector: "Jasa Profesional" },
  { code: "INDY", name: "Indika Energy Tbk", sector: "Batu Bara" },
  { code: "INET", name: "PT Sinergi Inti Andalan Prima Tbk.", sector: "Jasa Telekomunikasi" },
  { code: "INKP", name: "Indah Kiat Pulp & Paper Tbk", sector: "Perhutanan & Kertas" },
  { code: "INOV", name: "PT Inocycle Technology Group Tbk.", sector: "Pakaian & Barang Mewah" },
  { code: "INPC", name: "Bank Artha Graha Internasional Tbk", sector: "Bank" },
  {
    code: "INPP",
    name: "Indonesian Paradise Property Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "INPS", name: "PT Indah Prakasa Sentosa Tbk.", sector: "Minyak & Gas" },
  { code: "INRU", name: "Toba Pulp Lestari Tbk", sector: "Perhutanan & Kertas" },
  { code: "INTA", name: "Intraco Penta Tbk", sector: "Mesin" },
  { code: "INTD", name: "Inter-Delta Tbk", sector: "Perhutanan & Kertas" },
  { code: "INTP", name: "Indocement Tunggal Prakarsa Tbk", sector: "Material Konstruksi" },
  {
    code: "IOTF",
    name: "PT Sumber Sinergi Makmur Tbk",
    sector: "Perangkat, Instrumen & Komponen Elektronik",
  },
  { code: "IPAC", name: "PT Era Graharealty Tbk", sector: "Pengelola & Pengembang Real Estat" },
  {
    code: "IPCC",
    name: "PT Indonesia Kendaraan Terminal Tbk.",
    sector: "Operator Infrastruktur Transportasi",
  },
  {
    code: "IPCM",
    name: "PT Jasa Armada Indonesia Tbk.",
    sector: "Operator Infrastruktur Transportasi",
  },
  { code: "IPOL", name: "Indopoly Swakarsa Industry Tbk", sector: "Wadah & Kemasan" },
  { code: "IPPE", name: "PT Indo Pureco Pratama Tbk", sector: "Produk Makanan Pertanian" },
  { code: "IPTV", name: "PT MNC Vision Networks Tbk.", sector: "Media" },
  { code: "IRRA", name: "PT Itama Ranoraya Tbk.", sector: "Peralatan & Perlengkapan Kesehatan" },
  { code: "IRSX", name: "PT Folago Global Nusantara Tbk", sector: "Perangkat Lunak" },
  { code: "ISAP", name: "PT Isra Presisi Indonesia Tbk", sector: "Komponen Otomotif" },
  { code: "ISAT", name: "PT Indosat Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "ISEA", name: "PT Indo American Seafoods Tbk", sector: "Produk Makanan Pertanian" },
  { code: "ISSP", name: "PT Steel Pipe Industry of Indonesia Tbk", sector: "Logam & Mineral" },
  { code: "ITIC", name: "PT Indonesian Tobacco Tbk.", sector: "Rokok" },
  { code: "ITMA", name: "SUMBER ENERGI ANDALAN Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "ITMG", name: "Indo Tambangraya Megah Tbk", sector: "Batu Bara" },
  { code: "JARR", name: "PT Jhonlin Agro Raya Tbk", sector: "Produk Makanan Pertanian" },
  { code: "JAST", name: "PT Jasnita Telekomindo Tbk.", sector: "Jasa Telekomunikasi" },
  {
    code: "JATI",
    name: "PT Informasi Teknologi Indonesia Tbk.",
    sector: "Aplikasi & Jasa Internet",
  },
  { code: "JAWA", name: "Jaya Agra Wattie Tbk", sector: "Produk Makanan Pertanian" },
  { code: "JAYA", name: "PT Armada Berjaya Trans Tbk.", sector: "Logistik & Pengantaran" },
  { code: "JECC", name: "Jembo Cable Company Tbk", sector: "Kelistrikan" },
  { code: "JGLE", name: "PT Graha Andrasentra Propertindo Tbk.", sector: "Pariwisata & Rekreasi" },
  {
    code: "JIHD",
    name: "Jakarta International Hotels & Development Tbk",
    sector: "Pariwisata & Rekreasi",
  },
  { code: "JKON", name: "Jaya Konstruksi Manggala Pratama Tbk", sector: "Konstruksi Bangunan" },
  { code: "JMAS", name: "PT Asuransi Jiwa Syariah Jasa Mitra Abadi Tbk", sector: "Asuransi" },
  { code: "JPFA", name: "JAPFA Comfeed Indonesia Tbk", sector: "Produk Makanan Pertanian" },
  { code: "JRPT", name: "Jaya Real Property Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "JSKY", name: "PT Sky Energy Indonesia Tbk.", sector: "Peralatan Energi Alternatif" },
  { code: "JSMR", name: "PT Jasa Marga Tbk", sector: "Operator Infrastruktur Transportasi" },
  { code: "JSPT", name: "Jakarta Setiabudi Internasional Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "JTPE", name: "Jasuindo Tiga Perkasa Tbk", sector: "Jasa Komersial" },
  { code: "KAEF", name: "Kimia Farma Tbk.", sector: "Farmasi" },
  { code: "KAQI", name: "PT Jantra Grupo Indonesia Tbk", sector: "Komponen Otomotif" },
  { code: "KARW", name: "Meratus Jasa Prima Tbk", sector: "Operator Infrastruktur Transportasi" },
  { code: "KAYU", name: "PT Darmi Bersaudara Tbk.", sector: "Perhutanan & Kertas" },
  {
    code: "KBAG",
    name: "PT Karya Bersama Anugerah Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "KBLI", name: "KMI Wire and Cable Tbk", sector: "Kelistrikan" },
  { code: "KBLM", name: "Kabelindo Murni Tbk", sector: "Kelistrikan" },
  { code: "KBLV", name: "First Media Tbk", sector: "Jasa Telekomunikasi" },
  { code: "KBRI", name: "Kertas Basuki Rachmat Indonesia Tbk", sector: "Perhutanan & Kertas" },
  { code: "KDSI", name: "Kedawung Setia Industrial Tbk", sector: "Wadah & Kemasan" },
  { code: "KDTN", name: "PT Puri Sentul Permai Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "KEEN", name: "PT Kencana Energi Lestari Tbk.", sector: "Utilitas Listrik" },
  { code: "KEJU", name: "PT Mulia Boga Raya Tbk", sector: "Makanan Olahan" },
  { code: "KETR", name: "PT Ketrosden Triasmitra Tbk", sector: "Jasa Telekomunikasi" },
  {
    code: "KIAS",
    name: "Keramika Indonesia Assosiasi Tbk",
    sector: "Produk & Perlengkapan Bangunan",
  },
  { code: "KICI", name: "Kedaung Indah Can Tbk", sector: "Barang Rumah Tangga" },
  {
    code: "KIJA",
    name: "Kawasan Industri Jababeka Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "KING", name: "PT Hoffmen Cleanindo Tbk", sector: "Jasa Profesional" },
  { code: "KINO", name: "PT Kino Indonesia Tbk", sector: "Produk Perawatan Tubuh" },
  { code: "KIOS", name: "PT Kioson Komersial Indonesia Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "KJEN", name: "PT Krida Jaringan Nusantara Tbk.", sector: "Logistik & Pengantaran" },
  { code: "KKES", name: "PT Kusuma Kemindo Sentosa Tbk", sector: "Barang Kimia" },
  { code: "KKGI", name: "Resource Alam Indonesia Tbk", sector: "Batu Bara" },
  {
    code: "KLAS",
    name: "PT Pelayaran Kurnia Lautan Semesta Tbk",
    sector: "Logistik & Pengantaran",
  },
  { code: "KLBF", name: "Kalbe Farma Tbk", sector: "Farmasi" },
  { code: "KLIN", name: "PT Klinko Karya Imaji Tbk", sector: "Ritel Khusus" },
  {
    code: "KMDS",
    name: "PT Kurniamitra Duta Sentosa Tbk.",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "KMTR", name: "PT Kirana Megatara Tbk.", sector: "Perhutanan & Kertas" },
  { code: "KOBX", name: "Kobexindo Tractors Tbk", sector: "Mesin" },
  { code: "KOCI", name: "PT Kokoh Exa Nusantara", sector: "Pengelola & Pengembang Real Estat" },
  { code: "KOIN", name: "Kokoh Inti Arebama Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "KOKA", name: "PT Koka Indonesia Tbk.", sector: "Konstruksi Bangunan" },
  { code: "KONI", name: "Perdana Bangun Pusaka Tbk", sector: "Jasa Komersial" },
  { code: "KOPI", name: "PT Mitra Energi Persada Tbk", sector: "Minyak & Gas" },
  { code: "KOTA", name: "PT DMS Propertindo Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "KPIG", name: "MNC Tourism Indonesia Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "KRAS", name: "Krakatau Steel (Persero) Tbk", sector: "Logam & Mineral" },
  { code: "KREN", name: "PT Quantum Clovera Investama Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "KRYA", name: "PT Bangun Karya Perkasa Jaya Tbk", sector: "Konstruksi Bangunan" },
  {
    code: "KSIX",
    name: "PT Kentanix Supra International Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "KUAS", name: "PT Ace Oldfields Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "LABA", name: "PT Green Power Group Tbk", sector: "Mesin" },
  {
    code: "LABS",
    name: "PT UBC Medical Indonesia Tbk",
    sector: "Peralatan & Perlengkapan Kesehatan",
  },
  { code: "LAJU", name: "PT Jasa Berdikari Logistics Tbk", sector: "Logistik & Pengantaran" },
  {
    code: "LAND",
    name: "PT Trimitra Propertindo Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "LAPD", name: "Leyand International Tbk", sector: "Perdagangan Ritel Barang Primer" },
  {
    code: "LCGP",
    name: "PT Eureka Prima Jakarta Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "LCKM", name: "PT LCK Global Kedaton Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "LEAD", name: "PT Logindo Samudramakmur Tbk.", sector: "Minyak & Gas" },
  { code: "LFLO", name: "PT Imago Mulia Persada Tbk", sector: "Barang Rumah Tangga" },
  { code: "LIFE", name: "PT MSIG Life Insurance Indonesia Tbk.", sector: "Asuransi" },
  { code: "LINK", name: "PT Link Net Tbk.", sector: "Jasa Telekomunikasi" },
  { code: "LION", name: "Lion Metal Works Tbk", sector: "Jasa Komersial" },
  { code: "LIVE", name: "PT Homeco Victoria Makmur Tbk", sector: "Barang Rumah Tangga" },
  { code: "LMAS", name: "Limas Indonesia Makmur Tbk", sector: "Jasa & Konsultan TI" },
  { code: "LMAX", name: "PT Lupromax Pelumas Indonesia Tbk.", sector: "Komponen Otomotif" },
  { code: "LMPI", name: "Langgeng Makmur Industri Tbk", sector: "Barang Rumah Tangga" },
  { code: "LMSH", name: "Lionmesh Prima Tbk", sector: "Logam & Mineral" },
  { code: "LOPI", name: "PT Logisticsplus International Tbk", sector: "Logistik & Pengantaran" },
  { code: "LPCK", name: "Lippo Cikarang Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "LPGI", name: "Lippo General Insurance Tbk", sector: "Asuransi" },
  { code: "LPIN", name: "Multi Prima Sejahtera Tbk", sector: "Komponen Otomotif" },
  { code: "LPKR", name: "Lippo Karawaci Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "LPLI", name: "Star Pacific Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "LPPF", name: "Matahari Department Store Tbk", sector: "Department Store" },
  {
    code: "LPPS",
    name: "PT Lenox Pasifik Investama Tbk",
    sector: "Perusahaan Holding & Investasi",
  },
  {
    code: "LRNA",
    name: "PT Eka Sari Lorena Transport Tbk.",
    sector: "Pengangkutan Darat Penumpang",
  },
  { code: "LSIP", name: "PP London Sumatra Indonesia Tbk", sector: "Produk Makanan Pertanian" },
  { code: "LTLS", name: "PT Lautan Luas Tbk", sector: "Barang Kimia" },
  { code: "LUCK", name: "PT Sentral Mitra Informatika Tbk.", sector: "Perangkat Komputer" },
  { code: "LUCY", name: "PT Lima Dua Lima Tiga Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "MABA", name: "PT Marga Abhinaya Abadi Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "MAGP", name: "Multi Agro Gemilang Plantation Tbk", sector: "Produk Makanan Pertanian" },
  { code: "MAHA", name: "PT Mandiri Herindo Adiperkasa Tbk", sector: "Batu Bara" },
  { code: "MAIN", name: "Malindo Feedmill Tbk", sector: "Produk Makanan Pertanian" },
  { code: "MANG", name: "PT Manggung Polahraya Tbk", sector: "Konstruksi Bangunan" },
  { code: "MAPA", name: "PT Map Aktif Adiperkasa Tbk", sector: "Ritel Khusus" },
  { code: "MAPB", name: "PT Map Boga Adiperkasa Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "MAPI", name: "PT Mitra Adiperkasa Tbk", sector: "Ritel Khusus" },
  { code: "MARI", name: "PT Mahaka Radio Integra Tbk.", sector: "Media" },
  { code: "MARK", name: "PT Mark Dynamics Indonesia Tbk.", sector: "Mesin" },
  { code: "MASB", name: "PT Bank Multiarta Sentosa Tbk", sector: "Bank" },
  { code: "MAXI", name: "PT Maxindo Karya Anugerah Tbk", sector: "Makanan Olahan" },
  { code: "MAYA", name: "PT Bank Mayapada Internasional Tbk", sector: "Bank" },
  { code: "MBAP", name: "PT Mitrabara Adiperdana Tbk", sector: "Batu Bara" },
  { code: "MBMA", name: "PT Merdeka Battery Materials Tbk", sector: "Logam & Mineral" },
  { code: "MBSS", name: "Mitrabahtera Segara Sejati Tbk", sector: "Batu Bara" },
  { code: "MBTO", name: "Martina Berto Tbk", sector: "Produk Perawatan Tubuh" },
  { code: "MCAS", name: "PT M Cash Integrasi Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "MCOL", name: "PT Prima Andalan Mandiri Tbk", sector: "Batu Bara" },
  { code: "MCOR", name: "PT Bank China Construction Bank Indonesia Tbk", sector: "Bank" },
  { code: "MDIA", name: "PT Intermedia Capital Tbk.", sector: "Media" },
  { code: "MDIY", name: "PT Daya Intiguna Yasa Tbk", sector: "Ritel Khusus" },
  { code: "MDKA", name: "PT Merdeka Copper Gold Tbk.", sector: "Logam & Mineral" },
  { code: "MDKI", name: "PT Emdeki Utama Tbk", sector: "Barang Kimia" },
  { code: "MDLA", name: "PT Medela Potentia Tbk", sector: "Farmasi" },
  { code: "MDLN", name: "PT Modernland Realty Tbk.", sector: "Pengelola & Pengembang Real Estat" },
  { code: "MDRN", name: "Modern Internasional Tbk", sector: "Jasa Komersial" },
  { code: "MEDC", name: "PT Medco Energi Internasional Tbk", sector: "Minyak & Gas" },
  {
    code: "MEDS",
    name: "PT Hetzer Medical Indonesia Tbk",
    sector: "Peralatan & Perlengkapan Kesehatan",
  },
  { code: "MEGA", name: "Bank Mega Tbk", sector: "Bank" },
  { code: "MEJA", name: "PT Harta Djaya Karya Tbk", sector: "Barang Rumah Tangga" },
  {
    code: "MENN",
    name: "PT Menn Teknologi Indonesia Tbk.",
    sector: "Perangkat, Instrumen & Komponen Elektronik",
  },
  { code: "MERI", name: "PT Merry Riana Edukasi Tbk", sector: "Pendidikan & Jasa Penunjang" },
  { code: "MERK", name: "Merck Tbk", sector: "Farmasi" },
  {
    code: "META",
    name: "Nusantara Infrastructure Tbk",
    sector: "Operator Infrastruktur Transportasi",
  },
  { code: "MFIN", name: "PT Adira Dinamika Multi Finance Tbk", sector: "Pembiayaan Konsumen" },
  { code: "MFMI", name: "Multifiling Mitra Indonesia Tbk", sector: "Jasa Komersial" },
  { code: "MGLV", name: "PT Panca Anugrah Wisesa Tbk", sector: "Barang Rumah Tangga" },
  { code: "MGNA", name: "PT Magna Investama Mandiri Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "MGRO", name: "PT Mahkota Group Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "MHKI", name: "PT Multi Hanna Kreasindo Tbk", sector: "Jasa Komersial" },
  { code: "MICE", name: "Multi Indocitra Tbk", sector: "Barang Rumah Tangga" },
  { code: "MIDI", name: "Midi Utama Indonesia Tbk", sector: "Perdagangan Ritel Barang Primer" },
  { code: "MIKA", name: "PT Mitra Keluarga Karyasehat Tbk.", sector: "Penyedia Jasa Kesehatan" },
  { code: "MINA", name: "PT Sanurhasta Mitra Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "MINE", name: "PT Sinar Terang Mandiri Tbk", sector: "Logam & Mineral" },
  { code: "MIRA", name: "Mitra International Resources Tbk", sector: "Logistik & Pengantaran" },
  { code: "MITI", name: "Mitra Investindo Tbk", sector: "Logistik & Pengantaran" },
  {
    code: "MKAP",
    name: "PT Multikarya Asia Pasifik Raya Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  {
    code: "MKNT",
    name: "PT Mitra Komunikasi Nusantara Tbk.",
    sector: "Distributor Barang Konsumen",
  },
  { code: "MKPI", name: "Metropolitan Kentjana Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "MKTR", name: "PT Menthobi Karyatama Raya Tbk", sector: "Produk Makanan Pertanian" },
  { code: "MLBI", name: "Multi Bintang Indonesia Tbk", sector: "Minuman" },
  { code: "MLIA", name: "Mulia Industrindo Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "MLPL", name: "Multipolar Tbk", sector: "Perdagangan Ritel Barang Primer" },
  { code: "MLPT", name: "PT Multipolar Technology Tbk.", sector: "Jasa & Konsultan TI" },
  {
    code: "MMIX",
    name: "PT Multi Medika Internasional Tbk",
    sector: "Peralatan & Perlengkapan Kesehatan",
  },
  {
    code: "MMLP",
    name: "PT Mega Manunggal Property Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "MNCN", name: "Media Nusantara Citra Tbk", sector: "Media" },
  { code: "MOLI", name: "PT Madusari Murni Indah Tbk.", sector: "Barang Kimia" },
  { code: "MORA", name: "PT Mora Telematika Indonesia Tbk", sector: "Jasa Telekomunikasi" },
  { code: "MPIX", name: "PT Mitra Pedagang Indonesia Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "MPMX", name: "PT Mitra Pinasthika Mustika Tbk.", sector: "Ritel Khusus" },
  { code: "MPOW", name: "PT Megapower Makmur Tbk.", sector: "Utilitas Listrik" },
  { code: "MPPA", name: "Matahari Putra Prima Tbk", sector: "Perdagangan Ritel Barang Primer" },
  {
    code: "MPRO",
    name: "PT Maha Properti Indonesia Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "MPXL", name: "PT MPX Logistics International Tbk", sector: "Logistik & Pengantaran" },
  { code: "MRAT", name: "Mustika Ratu Tbk", sector: "Produk Perawatan Tubuh" },
  { code: "MREI", name: "Maskapai Reasuransi Indonesia Tbk", sector: "Asuransi" },
  {
    code: "MSIE",
    name: "PT Multisarana Intan Eduka Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "MSIN", name: "PT MNC Digital Entertainment Tbk", sector: "Hiburan & Film" },
  { code: "MSJA", name: "PT Multi Spunindo Jaya Tbk.", sector: "Produk Perawatan Tubuh" },
  { code: "MSKY", name: "MNC Sky Vision Tbk", sector: "Media" },
  { code: "MSTI", name: "PT Mastersystem Infotama Tbk.", sector: "Peralatan Jaringan" },
  { code: "MTDL", name: "Metrodata Electronics Tbk", sector: "Perangkat Komputer" },
  { code: "MTEL", name: "PT Dayamitra Telekomunikasi Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "MTFN", name: "Capitalinc Investment Tbk", sector: "Minyak & Gas" },
  { code: "MTLA", name: "Metropolitan Land Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "MTMH", name: "PT Murni Sadar Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "MTPS", name: "PT Meta Epsi Tbk.", sector: "Konstruksi Bangunan" },
  { code: "MTRA", name: "PT Mitra Pemuda Tbk.", sector: "Konstruksi Bangunan" },
  { code: "MTSM", name: "Metro Realty Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "MTWI", name: "PT Malacca Trust Wuwungan Insurance Tbk.", sector: "Asuransi" },
  { code: "MUTU", name: "PT Mutuagung Lestari Tbk", sector: "Jasa Profesional" },
  { code: "MYOH", name: "Samindo Resources Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "MYOR", name: "Mayora Indah Tbk", sector: "Makanan Olahan" },
  { code: "MYTX", name: "PT Asia Pacific Investama Tbk.", sector: "Pakaian & Barang Mewah" },
  {
    code: "NAIK",
    name: "PT Adiwarna Anugerah Abadi Tbk",
    sector: "Perdagangan Aneka Barang Perindustrian",
  },
  { code: "NANO", name: "PT Nanotech Indonesia Global Tbk", sector: "Produk Perawatan Tubuh" },
  {
    code: "NASA",
    name: "PT Andalan Perkasa Abadi Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "NASI", name: "PT Wahana Inti Makmur Tbk", sector: "Makanan Olahan" },
  { code: "NATO", name: "PT Surya Permata Andalan Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "NAYZ", name: "PT Hassana Boga Sejahtera Tbk", sector: "Makanan Olahan" },
  { code: "NCKL", name: "PT Trimegah Bangun Persada Tbk.", sector: "Logam & Mineral" },
  { code: "NELY", name: "Pelayaran Nelly Dwi Putri Tbk", sector: "Logistik & Pengantaran" },
  { code: "NEST", name: "PT Esta Indonesia Tbk", sector: "Produk Makanan Pertanian" },
  { code: "NETV", name: "PT MDTV Media Technologies Tbk", sector: "Media" },
  { code: "NFCX", name: "PT NFC Indonesia Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "NICE", name: "PT Adhi Kartiko Pratama Tbk", sector: "Logam & Mineral" },
  { code: "NICK", name: "PT Charnic Capital Tbk.", sector: "Perusahaan Holding & Investasi" },
  { code: "NICL", name: "PT PAM Mineral Tbk", sector: "Logam & Mineral" },
  { code: "NIKL", name: "Pelat Timah Nusantara Tbk", sector: "Logam & Mineral" },
  { code: "NINE", name: "PT Techno9 Indonesia Tbk", sector: "Perangkat Komputer" },
  {
    code: "NIRO",
    name: "City Retail Developments Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "NISP", name: "PT Bank OCBC NISP Tbk", sector: "Bank" },
  { code: "NOBU", name: "PT Bank Nationalnobu Tbk.", sector: "Bank" },
  { code: "NPGF", name: "PT Nusa Palapa Gemilang Tbk", sector: "Barang Kimia" },
  { code: "NRCA", name: "PT Nusa Raya Cipta Tbk.", sector: "Konstruksi Bangunan" },
  { code: "NSSS", name: "PT Nusantara Sawit Sejahtera Tbk", sector: "Produk Makanan Pertanian" },
  { code: "NTBK", name: "PT Nusatama Berkah Tbk", sector: "Mesin" },
  { code: "NUSA", name: "PT Sinergi Megah Internusa Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "NZIA", name: "PT Nusantara Almazia, Tbk.", sector: "Pengelola & Pengembang Real Estat" },
  { code: "OASA", name: "PT Maharaksa Biru Energi Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "OBAT", name: "PT Brigit Biofarmaka Teknologi Tbk", sector: "Farmasi" },
  { code: "OBMD", name: "PT OBM Drilchem Tbk", sector: "Barang Kimia" },
  { code: "OCAP", name: "ONIX CAPITAL Tbk", sector: "Perusahaan Holding & Investasi" },
  { code: "OILS", name: "PT Indo Oil Perkasa Tbk", sector: "Produk Makanan Pertanian" },
  { code: "OKAS", name: "Ancora Indonesia Resources Tbk", sector: "Barang Kimia" },
  { code: "OLIV", name: "PT Oscar Mitra Sukses Sejahtera Tbk", sector: "Barang Rumah Tangga" },
  {
    code: "OMED",
    name: "PT Jayamas Medica Industri Tbk",
    sector: "Peralatan & Perlengkapan Kesehatan",
  },
  {
    code: "OMRE",
    name: "Indonesia Prima Property Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "OPMS", name: "PT Optima Prima Metal Sinergi Tbk.", sector: "Logam & Mineral" },
  { code: "PACK", name: "PT Abadi Nusantara Hijau Investama Tbk", sector: "Wadah & Kemasan" },
  { code: "PADA", name: "PT Personel Alih Daya Tbk", sector: "Jasa Profesional" },
  { code: "PADI", name: "Minna Padi Investama Sekuritas Tbk", sector: "Jasa Investasi" },
  {
    code: "PALM",
    name: "PT Provident Investasi Bersama Tbk",
    sector: "Perusahaan Holding & Investasi",
  },
  { code: "PAMG", name: "PT Bima Sakti Pertiwi Tbk", sector: "Pengelola & Pengembang Real Estat" },
  {
    code: "PANI",
    name: "PT Pantai Indah Kapuk Dua Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "PANR", name: "Panorama Sentrawisata Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PANS", name: "Panin Sekuritas Tbk", sector: "Jasa Investasi" },
  { code: "PART", name: "PT Cipta Perdana Lancar Tbk", sector: "Komponen Otomotif" },
  { code: "PBID", name: "PT Panca Budi Idaman Tbk", sector: "Wadah & Kemasan" },
  { code: "PBRX", name: "Pan Brothers Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "PBSA", name: "PT Paramita Bangun Sarana Tbk", sector: "Konstruksi Bangunan" },
  { code: "PCAR", name: "PT Prima Cakrawala Abadi Tbk", sector: "Perdagangan Ritel Barang Primer" },
  { code: "PDES", name: "Destinasi Tirta Nusantara Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PDPP", name: "PT Primadaya Plastisindo Tbk", sector: "Wadah & Kemasan" },
  { code: "PEGE", name: "PT Panca Global Kapital Tbk.", sector: "Perusahaan Holding & Investasi" },
  { code: "PEHA", name: "PT Phapros Tbk", sector: "Farmasi" },
  { code: "PEVE", name: "PT Penta Valent Tbk", sector: "Farmasi" },
  { code: "PGAS", name: "PT Perusahaan Gas Negara Tbk.", sector: "Minyak & Gas" },
  { code: "PGEO", name: "PT Pertamina Geothermal Energy Tbk", sector: "Utilitas Listrik" },
  { code: "PGJO", name: "PT Bahtera Bumi Raya Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "PGLI", name: "Pembangunan Graha Lestari Indah Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PGUN", name: "PT Pradiksi Gunatama Tbk", sector: "Produk Makanan Pertanian" },
  { code: "PICO", name: "Pelangi Indah Canindo Tbk", sector: "Wadah & Kemasan" },
  { code: "PIPA", name: "PT Multi Makmur Lemindo Tbk.", sector: "Produk & Perlengkapan Bangunan" },
  { code: "PJAA", name: "Pembangunan Jaya Ancol Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PJHB", name: "PT Pelayaran Jaya Hidup Baru Tbk", sector: "Logistik & Pengantaran" },
  { code: "PKPK", name: "Paragon Karya Perkasa Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "PLAN", name: "PT Planet Properindo Jaya Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PLAS", name: "Polaris Investama Tbk", sector: "Perusahaan Holding & Investasi" },
  { code: "PLIN", name: "Plaza Indonesia Realty Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "PMJS", name: "PT Putra Mandiri Jembar Tbk", sector: "Ritel Khusus" },
  { code: "PMMP", name: "PT Panca Mitra Multiperdana Tbk.", sector: "Makanan Olahan" },
  {
    code: "PMUI",
    name: "PT Prima Multi Usaha Indonesia Tbk",
    sector: "Distributor Barang Konsumen",
  },
  { code: "PNBN", name: "Bank Pan Indonesia Tbk", sector: "Bank" },
  { code: "PNBS", name: "PT Bank Panin Dubai Syariah Tbk.", sector: "Bank" },
  { code: "PNGO", name: "PT Pinago Utama Tbk", sector: "Produk Makanan Pertanian" },
  { code: "PNIN", name: "Paninvest Tbk", sector: "Asuransi" },
  { code: "PNLF", name: "Panin Financial Tbk", sector: "Asuransi" },
  { code: "PNSE", name: "Pudjiadi & Sons Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "POLA", name: "PT Pool Advista Finance Tbk.", sector: "Pembiayaan Konsumen" },
  { code: "POLI", name: "PT Pollux Hotels Group Tbk", sector: "Pengelola & Pengembang Real Estat" },
  {
    code: "POLL",
    name: "PT Pollux Properties Indonesia Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "POLU", name: "PT Golden Flower Tbk.", sector: "Pakaian & Barang Mewah" },
  { code: "POLY", name: "Asia Pacific Fibers Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "POOL", name: "Pool Advista Indonesia Tbk", sector: "Perusahaan Holding & Investasi" },
  {
    code: "PORT",
    name: "PT Nusantara Pelabuhan Handal Tbk.",
    sector: "Operator Infrastruktur Transportasi",
  },
  {
    code: "POSA",
    name: "PT Bliss Properti Indonesia Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "POWR", name: "PT Cikarang Listrindo Tbk.", sector: "Utilitas Listrik" },
  { code: "PPGL", name: "PT Prima Globalindo Logistik Tbk.", sector: "Logistik & Pengantaran" },
  { code: "PPRE", name: "PT PP Presisi Tbk.", sector: "Konstruksi Bangunan" },
  { code: "PPRI", name: "PT Paperocks Indonesia Tbk.", sector: "Wadah & Kemasan" },
  { code: "PPRO", name: "PT PP Properti Tbk.", sector: "Pengelola & Pengembang Real Estat" },
  { code: "PRAY", name: "PT Famon Awal Bros Sedaya Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "PRDA", name: "PT Prodia Widyahusada Tbk.", sector: "Penyedia Jasa Kesehatan" },
  { code: "PRIM", name: "PT Royal Prima Tbk.", sector: "Penyedia Jasa Kesehatan" },
  { code: "PSAB", name: "J RESOURCES ASIA PASIFIK Tbk", sector: "Logam & Mineral" },
  { code: "PSAT", name: "PT Pancaran Samudera Transport Tbk", sector: "Batu Bara" },
  { code: "PSDN", name: "Prasidha Aneka Niaga Tbk", sector: "Makanan Olahan" },
  { code: "PSGO", name: "PT Palma Serasih Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "PSKT", name: "PT Red Planet Indonesia Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PSSI", name: "PT IMC Pelita Logistik Tbk", sector: "Batu Bara" },
  { code: "PTBA", name: "Bukit Asam Tbk", sector: "Batu Bara" },
  { code: "PTDU", name: "PT Djasa Ubersakti Tbk", sector: "Konstruksi Bangunan" },
  { code: "PTIS", name: "Indo Straits Tbk", sector: "Batu Bara" },
  { code: "PTMP", name: "PT Mitra Pack Tbk.", sector: "Mesin" },
  { code: "PTMR", name: "PT Master Print Tbk", sector: "Wadah & Kemasan" },
  { code: "PTPP", name: "PP (Persero) Tbk", sector: "Konstruksi Bangunan" },
  { code: "PTPS", name: "PT Pulau Subur Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "PTPW", name: "PT Pratama Widya Tbk.", sector: "Konstruksi Bangunan" },
  { code: "PTRO", name: "Petrosea Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "PTSN", name: "Sat Nusapersada Tbk", sector: "Peralatan Jaringan" },
  { code: "PTSP", name: "Pioneerindo Gourmet International Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "PUDP", name: "Pudjiadi Prestige Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "PURA", name: "PT Putra Rajawali Kencana Tbk.", sector: "Logistik & Pengantaran" },
  { code: "PURE", name: "PT Trinitan Metals and Minerals Tbk", sector: "Logam & Mineral" },
  { code: "PURI", name: "PT Puri Global Sukses Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "PWON", name: "Pakuwon Jati Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "PYFA", name: "PT Pyridam Farma Tbk", sector: "Farmasi" },
  { code: "PZZA", name: "PT Sarimelati Kencana Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "RAAM", name: "PT Tripar Multivision Plus Tbk.", sector: "Hiburan & Film" },
  { code: "RAFI", name: "PT Sari Kreasi Boga Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "RAJA", name: "Rukun Raharja Tbk", sector: "Minyak & Gas" },
  { code: "RALS", name: "Ramayana Lestari Sentosa Tbk", sector: "Department Store" },
  { code: "RANC", name: "Supra Boga Lestari Tbk", sector: "Perdagangan Ritel Barang Primer" },
  { code: "RATU", name: "PT Raharja Energi Cepu Tbk", sector: "Minyak & Gas" },
  {
    code: "RBMS",
    name: "Ristia Bintang Mahkotasejati Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "RCCC", name: "PT Utama Radar Cahaya Tbk", sector: "Logistik & Pengantaran" },
  { code: "RDTX", name: "Roda Vivatex Tbk", sector: "Pengelola & Pengembang Real Estat" },
  {
    code: "REAL",
    name: "PT Repower Asia Indonesia Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "RELF", name: "PT Graha Mitra Asia Tbk.", sector: "Pengelola & Pengembang Real Estat" },
  { code: "RELI", name: "Reliance Sekuritas Indonesia Tbk", sector: "Jasa Investasi" },
  {
    code: "RGAS",
    name: "PT Kian Santang Muliatama Tbk.",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "RICY", name: "Ricky Putra Globalindo Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "RIGS", name: "Rig Tenders Tbk", sector: "Batu Bara" },
  {
    code: "RIMO",
    name: "PT Rimo International Lestari Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  {
    code: "RISE",
    name: "PT Jaya Sukses Makmur Sentosa Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "RLCO", name: "PT Abadi Lestari Indonesia Tbk", sector: "Produk Makanan Pertanian" },
  { code: "RMKE", name: "PT RMK Energy Tbk", sector: "Batu Bara" },
  {
    code: "RMKO",
    name: "PT Royaltama Mulia Kontraktorindo Tbk.",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  {
    code: "ROCK",
    name: "PT Rockfields Properti Indonesia Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "RODA", name: "Pikko Land Development Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "RONY", name: "PT Aracord Nusantara Group Tbk", sector: "Konstruksi Bangunan" },
  { code: "ROTI", name: "PT Nippon Indosari Corpindo Tbk", sector: "Makanan Olahan" },
  { code: "RSCH", name: "PT Charlie Hospital Semarang Tbk.", sector: "Penyedia Jasa Kesehatan" },
  { code: "RSGK", name: "PT Kedoya Adyaraya Tbk", sector: "Penyedia Jasa Kesehatan" },
  {
    code: "RUIS",
    name: "Radiant Utama Interinsco Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "RUNS", name: "PT Global Sukses Solusi Tbk", sector: "Perangkat Lunak" },
  { code: "SAFE", name: "Steady Safe Tbk", sector: "Pengangkutan Darat Penumpang" },
  {
    code: "SAGE",
    name: "PT Saptausaha Gemilangindah Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "SAME", name: "Sarana Meditama Metropolitan Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "SAMF", name: "PT Saraswanti Anugerah Makmur Tbk.", sector: "Barang Kimia" },
  { code: "SAPX", name: "PT Satria Antaran Prima Tbk.", sector: "Logistik & Pengantaran" },
  { code: "SATU", name: "PT Kota Satu Properti Tbk.", sector: "Pengelola & Pengembang Real Estat" },
  {
    code: "SBAT",
    name: "PT Sejahtera Bintang Abadi Textile Tbk.",
    sector: "Pakaian & Barang Mewah",
  },
  { code: "SBMA", name: "PT Surya Biru Murni Acetylene Tbk", sector: "Barang Kimia" },
  { code: "SCCO", name: "PT Supreme Cable Manufacturing & Commerce Tbk", sector: "Kelistrikan" },
  { code: "SCMA", name: "Surya Citra Media Tbk", sector: "Media" },
  { code: "SCNP", name: "PT Selaras Citra Nusantara Perkasa Tbk", sector: "Barang Rumah Tangga" },
  { code: "SCPI", name: "PT Organon Pharma Indonesia Tbk", sector: "Farmasi" },
  { code: "SDMU", name: "Sidomulyo Selaras Tbk", sector: "Logistik & Pengantaran" },
  {
    code: "SDPC",
    name: "Millennium Pharmacon International Tbk",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "SDRA", name: "PT Bank Woori Saudara Indonesia 1906 Tbk", sector: "Bank" },
  { code: "SEMA", name: "PT Semacom Integrated Tbk", sector: "Peralatan Energi Alternatif" },
  { code: "SFAN", name: "PT Surya Fajar Capital Tbk", sector: "Perusahaan Holding & Investasi" },
  { code: "SGER", name: "PT Sumber Global Energy Tbk.", sector: "Batu Bara" },
  { code: "SGRO", name: "PT Prime Agri Resources Tbk", sector: "Produk Makanan Pertanian" },
  { code: "SHID", name: "Hotel Sahid Jaya Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "SHIP", name: "PT Sillo Maritime Perdana Tbk", sector: "Minyak & Gas" },
  {
    code: "SICO",
    name: "PT Sigma Energy Compressindo Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "SIDO", name: "PT Industri Jamu Dan Farmasi Sido Muncul Tbk", sector: "Farmasi" },
  {
    code: "SILO",
    name: "PT Siloam International Hospitals Tbk.",
    sector: "Penyedia Jasa Kesehatan",
  },
  { code: "SIMA", name: "Siwani Makmur Tbk", sector: "Wadah & Kemasan" },
  { code: "SIMP", name: "Salim Ivomas Pratama Tbk", sector: "Produk Makanan Pertanian" },
  { code: "SINI", name: "PT Singaraja Putra Tbk.", sector: "Produk & Perlengkapan Bangunan" },
  { code: "SIPD", name: "PT Sreeya Sewu Indonesia Tbk", sector: "Produk Makanan Pertanian" },
  { code: "SKBM", name: "Sekar Bumi Tbk", sector: "Makanan Olahan" },
  { code: "SKLT", name: "Sekar Laut Tbk", sector: "Makanan Olahan" },
  { code: "SKRN", name: "PT Superkrane Mitra Utama Tbk", sector: "Mesin" },
  { code: "SKYB", name: "PT Northcliff Citranusa Indonesia Tbk.", sector: "Perangkat Lunak" },
  { code: "SLIS", name: "PT Gaya Abadi Sempurna Tbk", sector: "Ritel Khusus" },
  {
    code: "SMAR",
    name: "PT Sinar Mas Agro Resources and Technology Tbk",
    sector: "Produk Makanan Pertanian",
  },
  { code: "SMBR", name: "PT Semen Baturaja (Persero) Tbk", sector: "Material Konstruksi" },
  { code: "SMCB", name: "PT Solusi Bangun Indonesia Tbk", sector: "Material Konstruksi" },
  { code: "SMDM", name: "Suryamas Dutamakmur Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "SMDR", name: "Samudera Indonesia Tbk", sector: "Logistik & Pengantaran" },
  { code: "SMGA", name: "PT Sumber Mineral Global Abadi Tbk", sector: "Logam & Mineral" },
  { code: "SMGR", name: "Semen Indonesia (Persero) Tbk", sector: "Material Konstruksi" },
  { code: "SMIL", name: "PT Sarana Mitra Luas Tbk", sector: "Mesin" },
  { code: "SMKL", name: "PT Satyamitra Kemas Lestari Tbk", sector: "Wadah & Kemasan" },
  { code: "SMKM", name: "PT Sumber Mas Konstruksi Tbk", sector: "Konstruksi Bangunan" },
  { code: "SMLE", name: "PT Sinergi Multi Lestarindo Tbk", sector: "Barang Kimia" },
  { code: "SMMA", name: "PT Sinar Mas Multiartha Tbk", sector: "Perusahaan Holding & Investasi" },
  { code: "SMMT", name: "GOLDEN EAGLE ENERGY Tbk", sector: "Batu Bara" },
  { code: "SMRA", name: "PT Summarecon Agung Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "SMRU", name: "SMR Utama Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "SMSM", name: "Selamat Sempurna Tbk", sector: "Komponen Otomotif" },
  { code: "SNLK", name: "PT Sunter Lakeside Hotel Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "SOCI", name: "PT Soechi Lines Tbk.", sector: "Minyak & Gas" },
  { code: "SOFA", name: "PT Solusi Environment Asia Tbk", sector: "Barang Rumah Tangga" },
  { code: "SOHO", name: "PT Soho Global Health Tbk", sector: "Farmasi" },
  { code: "SOLA", name: "PT Xolare RCR Energy Tbk", sector: "Material Konstruksi" },
  { code: "SONA", name: "Sona Topas Tourism Industry Tbk", sector: "Department Store" },
  { code: "SOSS", name: "PT Shield On Service Tbk.", sector: "Jasa Profesional" },
  { code: "SOTS", name: "PT Satria Mega Kencana Tbk.", sector: "Pariwisata & Rekreasi" },
  { code: "SOUL", name: "PT Mitra Tirta Buwana Tbk", sector: "Minuman" },
  { code: "SPMA", name: "Suparma Tbk", sector: "Wadah & Kemasan" },
  { code: "SPRE", name: "PT Soraya Berjaya Indonesia Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "SPTO", name: "PT Surya Pertiwi Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "SQMI", name: "Wilton Makmur Indonesia Tbk", sector: "Logam & Mineral" },
  { code: "SRAJ", name: "Sejahteraraya Anugrahjaya Tbk", sector: "Penyedia Jasa Kesehatan" },
  { code: "SRIL", name: "PT Sri Rejeki Isman Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "SRSN", name: "Indo Acidatama Tbk", sector: "Barang Kimia" },
  {
    code: "SRTG",
    name: "PT Saratoga Investama Sedaya Tbk.",
    sector: "Perusahaan Holding & Investasi",
  },
  { code: "SSIA", name: "PT Surya Semesta Internusa Tbk", sector: "Konstruksi Bangunan" },
  { code: "SSMS", name: "PT Sawit Sumbermas Sarana Tbk.", sector: "Produk Makanan Pertanian" },
  { code: "SSTM", name: "Sunson Textile Manufacturer Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "STAA", name: "PT Sumber Tani Agung Resources Tbk", sector: "Produk Makanan Pertanian" },
  { code: "STAR", name: "PT Buana Artha Anugerah Tbk.", sector: "Perusahaan Holding & Investasi" },
  { code: "STRK", name: "PT Lovina Beach Brewery Tbk.", sector: "Minuman" },
  { code: "STTP", name: "PT Siantar Top Tbk", sector: "Makanan Olahan" },
  { code: "SUGI", name: "Sugih Energy Tbk", sector: "Minyak & Gas" },
  { code: "SULI", name: "PT SLJ Global Tbk", sector: "Perhutanan & Kertas" },
  { code: "SUNI", name: "PT Sunindo Pratama Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "SUPA", name: "PT Super Bank Indonesia Tbk", sector: "Bank" },
  { code: "SUPR", name: "Solusi Tunas Pratama Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "SURE", name: "PT Super Energy Tbk.", sector: "Minyak & Gas" },
  {
    code: "SURI",
    name: "PT Maja Agung Latexindo Tbk.",
    sector: "Peralatan & Perlengkapan Kesehatan",
  },
  { code: "SWAT", name: "PT Sriwahana Adityakarta Tbk.", sector: "Perhutanan & Kertas" },
  { code: "SWID", name: "PT Saraswanti Indoland Development Tbk", sector: "Pariwisata & Rekreasi" },
  { code: "TALF", name: "PT Tunas Alfin Tbk", sector: "Wadah & Kemasan" },
  { code: "TAMA", name: "PT Lancartama Sejati Tbk.", sector: "Konstruksi Bangunan" },
  {
    code: "TAMU",
    name: "PT Pelayaran Tamarin Samudra Tbk.",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "TAPG", name: "PT Triputra Agro Persada Tbk.", sector: "Produk Makanan Pertanian" },
  {
    code: "TARA",
    name: "PT Agung Semesta Sejahtera Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "TAXI", name: "Express Transindo Utama Tbk", sector: "Pengangkutan Darat Penumpang" },
  { code: "TAYS", name: "PT Jaya Swarasa Agung Tbk", sector: "Makanan Olahan" },
  {
    code: "TBIG",
    name: "PT Tower Bersama Infrastructure Tbk",
    sector: "Jasa Telekomunikasi Nirkabel",
  },
  { code: "TBLA", name: "Tunas Baru Lampung Tbk", sector: "Makanan Olahan" },
  { code: "TBMS", name: "Tembaga Mulia Semanan Tbk", sector: "Logam & Mineral" },
  { code: "TCID", name: "Mandom Indonesia Tbk", sector: "Produk Perawatan Tubuh" },
  { code: "TCPI", name: "PT Transcoal Pacific Tbk.", sector: "Batu Bara" },
  { code: "TDPM", name: "PT Tianrong Chemicals Industry Tbk", sector: "Barang Kimia" },
  { code: "TEBE", name: "PT Dana Brata Luhur Tbk.", sector: "Batu Bara" },
  { code: "TECH", name: "PT Indosterling Technomedia Tbk", sector: "Jasa & Konsultan TI" },
  { code: "TELE", name: "PT Omni Inovasi Indonesia Tbk", sector: "Distributor Barang Konsumen" },
  { code: "TFAS", name: "PT Telefast Indonesia Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "TFCO", name: "Tifico Fiber Indonesia Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "TGKA", name: "Tigaraksa Satria Tbk", sector: "Makanan Olahan" },
  { code: "TGRA", name: "PT Terregra Asia Energy", sector: "Utilitas Listrik" },
  { code: "TGUK", name: "PT Platinum Wahab Nusantara Tbk.", sector: "Makanan Olahan" },
  { code: "TIFA", name: "KDB Tifa Finance Tbk", sector: "Pembiayaan Konsumen" },
  { code: "TINS", name: "PT Timah Tbk.", sector: "Logam & Mineral" },
  { code: "TIRA", name: "Tira Austenite Tbk", sector: "Perdagangan Aneka Barang Perindustrian" },
  { code: "TIRT", name: "Tirta Mahakam Resources Tbk", sector: "Perhutanan & Kertas" },
  { code: "TKIM", name: "Pabrik Kertas Tjiwi Kimia Tbk", sector: "Perhutanan & Kertas" },
  { code: "TLDN", name: "PT Teladan Prima Agro Tbk", sector: "Produk Makanan Pertanian" },
  { code: "TLKM", name: "PT Telkom Indonesia (Persero) Tbk", sector: "Jasa Telekomunikasi" },
  { code: "TMAS", name: "PT Temas Tbk.", sector: "Logistik & Pengantaran" },
  { code: "TMPO", name: "Tempo Inti Media Tbk", sector: "Media" },
  { code: "TNCA", name: "PT Trimuda Nuansa Citra Tbk.", sector: "Logistik & Pengantaran" },
  { code: "TOBA", name: "PT TBS Energi Utama Tbk", sector: "Batu Bara" },
  { code: "TOOL", name: "PT Rohartindo Nusantara Luas Tbk", sector: "Ritel Khusus" },
  { code: "TOPS", name: "PT Totalindo Eka Persada Tbk.", sector: "Konstruksi Bangunan" },
  { code: "TOSK", name: "PT Topindo Solusi Komunika Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "TOTL", name: "Total Bangun Persada Tbk", sector: "Konstruksi Bangunan" },
  { code: "TOTO", name: "Surya Toto Indonesia Tbk", sector: "Produk & Perlengkapan Bangunan" },
  { code: "TOWR", name: "Sarana Menara Nusantara Tbk", sector: "Jasa Telekomunikasi Nirkabel" },
  { code: "TOYS", name: "PT Sunindo Adipersada Tbk.", sector: "Peralatan Olah Raga & Barang Hobi" },
  { code: "TPIA", name: "PT Chandra Asri Pacific Tbk", sector: "Barang Kimia" },
  { code: "TPMA", name: "Trans Power Marine Tbk", sector: "Batu Bara" },
  { code: "TRAM", name: "Trada Alam Minera Tbk.", sector: "Batu Bara" },
  { code: "TRGU", name: "PT Cerestar Indonesia Tbk", sector: "Makanan Olahan" },
  {
    code: "TRIL",
    name: "Triwira Insanlestari Tbk",
    sector: "Perdagangan Aneka Barang Perindustrian",
  },
  { code: "TRIM", name: "PT Trimegah Sekuritas Indonesia Tbk", sector: "Jasa Investasi" },
  {
    code: "TRIN",
    name: "PT Perintis Triniti Properti Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "TRIO", name: "Trikomsel Oke Tbk", sector: "Ritel Khusus" },
  { code: "TRIS", name: "Trisula International Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "TRJA", name: "PT Transkon Jaya Tbk.", sector: "Pengangkutan Darat Penumpang" },
  { code: "TRON", name: "PT Teknologi Karya Digital Nusa Tbk.", sector: "Perangkat Lunak" },
  { code: "TRST", name: "Trias Sentosa Tbk", sector: "Wadah & Kemasan" },
  { code: "TRUE", name: "PT Triniti Dinamik Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "TRUK", name: "PT Guna Timur Raya Tbk.", sector: "Logistik & Pengantaran" },
  { code: "TRUS", name: "Trust Finance Indonesia Tbk", sector: "Pembiayaan Konsumen" },
  { code: "TSPC", name: "Tempo Scan Pacific Tbk", sector: "Farmasi" },
  { code: "TUGU", name: "PT Asuransi Tugu Pratama Indonesia Tbk", sector: "Asuransi" },
  { code: "TYRE", name: "PT King Tire Indonesia Tbk.", sector: "Komponen Otomotif" },
  { code: "UANG", name: "PT Pakuan Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "UCID", name: "PT Uni-Charm Indonesia Tbk.", sector: "Produk Perawatan Tubuh" },
  { code: "UDNG", name: "PT Agro Bahari Nusantara Tbk", sector: "Produk Makanan Pertanian" },
  { code: "UFOE", name: "PT Damai Sejahtera Abadi Tbk", sector: "Ritel Khusus" },
  {
    code: "ULTJ",
    name: "PT Ultrajaya Milk Industry & Trading Company Tbk",
    sector: "Makanan Olahan",
  },
  { code: "UNIC", name: "Unggul Indah Cahaya Tbk", sector: "Barang Kimia" },
  { code: "UNIQ", name: "PT Ulima Nitra Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "UNIT", name: "Nusantara Inti Corpora Tbk", sector: "Pakaian & Barang Mewah" },
  { code: "UNSP", name: "Bakrie Sumatera Plantations Tbk", sector: "Produk Makanan Pertanian" },
  {
    code: "UNTD",
    name: "PT Terang Dunia Internusa Tbk.",
    sector: "Peralatan Olah Raga & Barang Hobi",
  },
  { code: "UNTR", name: "United Tractors Tbk", sector: "Mesin" },
  { code: "UNVR", name: "Unilever Indonesia Tbk", sector: "Produk Perawatan Tubuh" },
  {
    code: "URBN",
    name: "PT Urban Jakarta Propertindo Tbk.",
    sector: "Pengelola & Pengembang Real Estat",
  },
  { code: "UVCR", name: "PT Trimegah Karya Pratama Tbk.", sector: "Aplikasi & Jasa Internet" },
  { code: "VAST", name: "PT Vastland Indonesia Tbk", sector: "Pengelola & Pengembang Real Estat" },
  { code: "VERN", name: "PT Verona Indah Pictures Tbk", sector: "Hiburan & Film" },
  { code: "VICI", name: "PT Victoria Care Indonesia Tbk", sector: "Produk Perawatan Tubuh" },
  { code: "VICO", name: "PT Victoria Investama Tbk.", sector: "Perusahaan Holding & Investasi" },
  { code: "VINS", name: "PT Victoria Insurance Tbk.", sector: "Asuransi" },
  { code: "VISI", name: "PT Satu Visi Putra Tbk.", sector: "Jasa Komersial" },
  { code: "VIVA", name: "PT Visi Media Asia Tbk", sector: "Media" },
  { code: "VKTR", name: "PT VKTR Teknologi Mobilitas Tbk", sector: "Komponen Otomotif" },
  { code: "VOKS", name: "Voksel Electric Tbk", sector: "Kelistrikan" },
  { code: "VRNA", name: "PT Mizuho Leasing Indonesia Tbk", sector: "Pembiayaan Konsumen" },
  { code: "VTNY", name: "PT Venteny Fortuna International Tbk", sector: "Pembiayaan Konsumen" },
  { code: "WAPO", name: "Wahana Pronatural Tbk", sector: "Produk Makanan Pertanian" },
  { code: "WEGE", name: "PT Wijaya Karya Bangunan Gedung Tbk.", sector: "Konstruksi Bangunan" },
  {
    code: "WEHA",
    name: "PT WEHA Transportasi Indonesia Tbk",
    sector: "Pengangkutan Darat Penumpang",
  },
  { code: "WGSH", name: "PT Wira Global Solusi Tbk", sector: "Perangkat Lunak" },
  {
    code: "WICO",
    name: "Wicaksana Overseas International Tbk",
    sector: "Perdagangan Ritel Barang Primer",
  },
  { code: "WIDI", name: "PT Widiant Jaya Krenindo Tbk.", sector: "Mesin" },
  { code: "WIFI", name: "PT Solusi Sinergi Digital Tbk", sector: "Aplikasi & Jasa Internet" },
  { code: "WIIM", name: "Wismilak Inti Makmur Tbk", sector: "Rokok" },
  { code: "WIKA", name: "PT Wijaya Karya (Persero) Tbk", sector: "Konstruksi Bangunan" },
  { code: "WINE", name: "PT Hatten Bali Tbk", sector: "Minuman" },
  {
    code: "WINR",
    name: "PT Winner Nusantara Jaya Tbk",
    sector: "Pengelola & Pengembang Real Estat",
  },
  {
    code: "WINS",
    name: "Wintermar Offshore Marine Tbk",
    sector: "Pendukung Minyak, Gas & Batu Bara",
  },
  { code: "WIRG", name: "PT WIR ASIA Tbk", sector: "Perangkat Lunak" },
  { code: "WMPP", name: "PT Widodo Makmur Perkasa Tbk", sector: "Produk Makanan Pertanian" },
  { code: "WMUU", name: "PT Widodo Makmur Unggas Tbk", sector: "Produk Makanan Pertanian" },
  { code: "WOMF", name: "PT Wahana Ottomitra Multiartha Tbk", sector: "Pembiayaan Konsumen" },
  { code: "WOOD", name: "PT Integra Indocabinet Tbk", sector: "Barang Rumah Tangga" },
  { code: "WOWS", name: "PT Ginting Jaya Energi Tbk", sector: "Pendukung Minyak, Gas & Batu Bara" },
  { code: "WSBP", name: "PT Waskita Beton Precast Tbk.", sector: "Material Konstruksi" },
  { code: "WSKT", name: "PT Waskita Karya (Persero) Tbk", sector: "Konstruksi Bangunan" },
  { code: "WTON", name: "Wijaya Karya Beton", sector: "Material Konstruksi" },
  { code: "YELO", name: "PT Yelooo Integra Datanet Tbk.", sector: "Distributor Barang Konsumen" },
  { code: "YOII", name: "PT Asuransi Digital Bersama Tbk", sector: "Asuransi" },
  { code: "YPAS", name: "Yanaprima Hastapersada Tbk", sector: "Wadah & Kemasan" },
  { code: "YULE", name: "Yulie Sekuritas Indonesia Tbk", sector: "Jasa Investasi" },
  { code: "YUPI", name: "PT Yupi Indo Jelly Gum Tbk", sector: "Makanan Olahan" },
  { code: "ZATA", name: "PT Bersama Zatta Jaya Tbk", sector: "Ritel Khusus" },
  { code: "ZBRA", name: "PT Dosni Roha Indonesia Tbk", sector: "Perusahaan Holding Multi-sektor" },
  { code: "ZINC", name: "PT Kapuas Prima Coal Tbk", sector: "Logam & Mineral" },
  { code: "ZONE", name: "PT Mega Perintis Tbk.", sector: "Ritel Khusus" },
  { code: "ZYRX", name: "PT Zyrexindo Mandiri Buana Tbk", sector: "Perangkat Komputer" },
];

export const IDX_TICKERS: string[] = IDX_EMITEN.map((e) => e.code);

export function toYahoo(ticker: string): string {
  return `${ticker.toUpperCase().replace(/\.JK$/, "")}.JK`;
}

export function fromYahoo(symbol: string): string {
  return symbol.replace(/\.JK$/, "");
}
