/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppMarketInsightRouteImport } from './routes/_app.market-insight'
import { Route as AppEkonomiRouteImport } from './routes/_app.ekonomi'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppAnalisisRouteImport } from './routes/_app.analisis'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppEkonomiIndexRouteImport } from './routes/_app.ekonomi.index'
import { Route as AppIdxScreenerRouteImport } from './routes/_app.idx.screener'
import { Route as AppIdxMarketsRouteImport } from './routes/_app.idx.markets'
import { Route as AppEkonomiMacroRouteImport } from './routes/_app.ekonomi.macro'
import { Route as AppEkonomiKomoditasRouteImport } from './routes/_app.ekonomi.komoditas'
import { Route as AppEkonomiGlobalRouteImport } from './routes/_app.ekonomi.global'
import { Route as AppEkonomiCalendarRouteImport } from './routes/_app.ekonomi.calendar'
import { Route as AppEkonomiAiBriefRouteImport } from './routes/_app.ekonomi.ai-brief'
import { Route as AppAnalisisValuationRouteImport } from './routes/_app.analisis.valuation'
import { Route as AppAnalisisTechnicalRouteImport } from './routes/_app.analisis.technical'
import { Route as AppAnalisisScreenerRouteImport } from './routes/_app.analisis.screener'
import { Route as AppAnalisisPortfolioRouteImport } from './routes/_app.analisis.portfolio'
import { Route as AppAnalisisEarningsRouteImport } from './routes/_app.analisis.earnings'
import { Route as AppAnalisisDividendRouteImport } from './routes/_app.analisis.dividend'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminUserPortfoliosRouteImport } from './routes/_app.admin.user-portfolios'
import { Route as AppAdminTransactionsRouteImport } from './routes/_app.admin.transactions'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminSecurityRouteImport } from './routes/_app.admin.security'
import { Route as AppAdminPricesRouteImport } from './routes/_app.admin.prices'
import { Route as AppAdminInsightAiRouteImport } from './routes/_app.admin.insight-ai'
import { Route as AppAdminInsightRouteImport } from './routes/_app.admin.insight'
import { Route as AppAdminHoldingsRouteImport } from './routes/_app.admin.holdings'
import { Route as AppAdminBroadcastRouteImport } from './routes/_app.admin.broadcast'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketInsightRoute = AppMarketInsightRouteImport.update({
  id: '/market-insight',
  path: '/market-insight',
  getParentRoute: () => AppRoute,
} as any)
const AppEkonomiRoute = AppEkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalisisRoute = AppAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppEkonomiIndexRoute = AppEkonomiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEkonomiRoute,
} as any)
const AppIdxScreenerRoute = AppIdxScreenerRouteImport.update({
  id: '/idx/screener',
  path: '/idx/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppIdxMarketsRoute = AppIdxMarketsRouteImport.update({
  id: '/idx/markets',
  path: '/idx/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppEkonomiMacroRoute = AppEkonomiMacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => AppEkonomiRoute,
} as any)
const AppEkonomiKomoditasRoute = AppEkonomiKomoditasRouteImport.update({
  id: '/komoditas',
  path: '/komoditas',
  getParentRoute: () => AppEkonomiRoute,
} as any)
const AppEkonomiGlobalRoute = AppEkonomiGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => AppEkonomiRoute,
} as any)
const AppEkonomiCalendarRoute = AppEkonomiCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppEkonomiRoute,
} as any)
const AppEkonomiAiBriefRoute = AppEkonomiAiBriefRouteImport.update({
  id: '/ai-brief',
  path: '/ai-brief',
  getParentRoute: () => AppEkonomiRoute,
} as any)
const AppAnalisisValuationRoute = AppAnalisisValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AppAnalisisRoute,
} as any)
const AppAnalisisTechnicalRoute = AppAnalisisTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => AppAnalisisRoute,
} as any)
const AppAnalisisScreenerRoute = AppAnalisisScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppAnalisisRoute,
} as any)
const AppAnalisisPortfolioRoute = AppAnalisisPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppAnalisisRoute,
} as any)
const AppAnalisisEarningsRoute = AppAnalisisEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppAnalisisRoute,
} as any)
const AppAnalisisDividendRoute = AppAnalisisDividendRouteImport.update({
  id: '/dividend',
  path: '/dividend',
  getParentRoute: () => AppAnalisisRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUserPortfoliosRoute = AppAdminUserPortfoliosRouteImport.update({
  id: '/user-portfolios',
  path: '/user-portfolios',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTransactionsRoute = AppAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPricesRoute = AppAdminPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInsightAiRoute = AppAdminInsightAiRouteImport.update({
  id: '/insight-ai',
  path: '/insight-ai',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInsightRoute = AppAdminInsightRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHoldingsRoute = AppAdminHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBroadcastRoute = AppAdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/analisis': typeof AppAnalisisRouteWithChildren
  '/community': typeof AppCommunityRoute
  '/ekonomi': typeof AppEkonomiRouteWithChildren
  '/market-insight': typeof AppMarketInsightRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/broadcast': typeof AppAdminBroadcastRoute
  '/admin/holdings': typeof AppAdminHoldingsRoute
  '/admin/insight': typeof AppAdminInsightRoute
  '/admin/insight-ai': typeof AppAdminInsightAiRoute
  '/admin/prices': typeof AppAdminPricesRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/transactions': typeof AppAdminTransactionsRoute
  '/admin/user-portfolios': typeof AppAdminUserPortfoliosRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/analisis/dividend': typeof AppAnalisisDividendRoute
  '/analisis/earnings': typeof AppAnalisisEarningsRoute
  '/analisis/portfolio': typeof AppAnalisisPortfolioRoute
  '/analisis/screener': typeof AppAnalisisScreenerRoute
  '/analisis/technical': typeof AppAnalisisTechnicalRoute
  '/analisis/valuation': typeof AppAnalisisValuationRoute
  '/ekonomi/ai-brief': typeof AppEkonomiAiBriefRoute
  '/ekonomi/calendar': typeof AppEkonomiCalendarRoute
  '/ekonomi/global': typeof AppEkonomiGlobalRoute
  '/ekonomi/komoditas': typeof AppEkonomiKomoditasRoute
  '/ekonomi/macro': typeof AppEkonomiMacroRoute
  '/idx/markets': typeof AppIdxMarketsRoute
  '/idx/screener': typeof AppIdxScreenerRoute
  '/ekonomi/': typeof AppEkonomiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/analisis': typeof AppAnalisisRouteWithChildren
  '/community': typeof AppCommunityRoute
  '/market-insight': typeof AppMarketInsightRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/broadcast': typeof AppAdminBroadcastRoute
  '/admin/holdings': typeof AppAdminHoldingsRoute
  '/admin/insight': typeof AppAdminInsightRoute
  '/admin/insight-ai': typeof AppAdminInsightAiRoute
  '/admin/prices': typeof AppAdminPricesRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/transactions': typeof AppAdminTransactionsRoute
  '/admin/user-portfolios': typeof AppAdminUserPortfoliosRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/analisis/dividend': typeof AppAnalisisDividendRoute
  '/analisis/earnings': typeof AppAnalisisEarningsRoute
  '/analisis/portfolio': typeof AppAnalisisPortfolioRoute
  '/analisis/screener': typeof AppAnalisisScreenerRoute
  '/analisis/technical': typeof AppAnalisisTechnicalRoute
  '/analisis/valuation': typeof AppAnalisisValuationRoute
  '/ekonomi/ai-brief': typeof AppEkonomiAiBriefRoute
  '/ekonomi/calendar': typeof AppEkonomiCalendarRoute
  '/ekonomi/global': typeof AppEkonomiGlobalRoute
  '/ekonomi/komoditas': typeof AppEkonomiKomoditasRoute
  '/ekonomi/macro': typeof AppEkonomiMacroRoute
  '/idx/markets': typeof AppIdxMarketsRoute
  '/idx/screener': typeof AppIdxScreenerRoute
  '/ekonomi': typeof AppEkonomiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/request-access': typeof RequestAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/analisis': typeof AppAnalisisRouteWithChildren
  '/_app/community': typeof AppCommunityRoute
  '/_app/ekonomi': typeof AppEkonomiRouteWithChildren
  '/_app/market-insight': typeof AppMarketInsightRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/broadcast': typeof AppAdminBroadcastRoute
  '/_app/admin/holdings': typeof AppAdminHoldingsRoute
  '/_app/admin/insight': typeof AppAdminInsightRoute
  '/_app/admin/insight-ai': typeof AppAdminInsightAiRoute
  '/_app/admin/prices': typeof AppAdminPricesRoute
  '/_app/admin/security': typeof AppAdminSecurityRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/transactions': typeof AppAdminTransactionsRoute
  '/_app/admin/user-portfolios': typeof AppAdminUserPortfoliosRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/analisis/dividend': typeof AppAnalisisDividendRoute
  '/_app/analisis/earnings': typeof AppAnalisisEarningsRoute
  '/_app/analisis/portfolio': typeof AppAnalisisPortfolioRoute
  '/_app/analisis/screener': typeof AppAnalisisScreenerRoute
  '/_app/analisis/technical': typeof AppAnalisisTechnicalRoute
  '/_app/analisis/valuation': typeof AppAnalisisValuationRoute
  '/_app/ekonomi/ai-brief': typeof AppEkonomiAiBriefRoute
  '/_app/ekonomi/calendar': typeof AppEkonomiCalendarRoute
  '/_app/ekonomi/global': typeof AppEkonomiGlobalRoute
  '/_app/ekonomi/komoditas': typeof AppEkonomiKomoditasRoute
  '/_app/ekonomi/macro': typeof AppEkonomiMacroRoute
  '/_app/idx/markets': typeof AppIdxMarketsRoute
  '/_app/idx/screener': typeof AppIdxScreenerRoute
  '/_app/ekonomi/': typeof AppEkonomiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/request-access'
    | '/reset-password'
    | '/activity'
    | '/admin'
    | '/analisis'
    | '/community'
    | '/ekonomi'
    | '/market-insight'
    | '/portfolio'
    | '/settings'
    | '/watchlist'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/holdings'
    | '/admin/insight'
    | '/admin/insight-ai'
    | '/admin/prices'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/user-portfolios'
    | '/admin/users'
    | '/analisis/dividend'
    | '/analisis/earnings'
    | '/analisis/portfolio'
    | '/analisis/screener'
    | '/analisis/technical'
    | '/analisis/valuation'
    | '/ekonomi/ai-brief'
    | '/ekonomi/calendar'
    | '/ekonomi/global'
    | '/ekonomi/komoditas'
    | '/ekonomi/macro'
    | '/idx/markets'
    | '/idx/screener'
    | '/ekonomi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/request-access'
    | '/reset-password'
    | '/activity'
    | '/admin'
    | '/analisis'
    | '/community'
    | '/market-insight'
    | '/portfolio'
    | '/settings'
    | '/watchlist'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/holdings'
    | '/admin/insight'
    | '/admin/insight-ai'
    | '/admin/prices'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/user-portfolios'
    | '/admin/users'
    | '/analisis/dividend'
    | '/analisis/earnings'
    | '/analisis/portfolio'
    | '/analisis/screener'
    | '/analisis/technical'
    | '/analisis/valuation'
    | '/ekonomi/ai-brief'
    | '/ekonomi/calendar'
    | '/ekonomi/global'
    | '/ekonomi/komoditas'
    | '/ekonomi/macro'
    | '/idx/markets'
    | '/idx/screener'
    | '/ekonomi'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/request-access'
    | '/reset-password'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/analisis'
    | '/_app/community'
    | '/_app/ekonomi'
    | '/_app/market-insight'
    | '/_app/portfolio'
    | '/_app/settings'
    | '/_app/watchlist'
    | '/_app/admin/audit'
    | '/_app/admin/broadcast'
    | '/_app/admin/holdings'
    | '/_app/admin/insight'
    | '/_app/admin/insight-ai'
    | '/_app/admin/prices'
    | '/_app/admin/security'
    | '/_app/admin/settings'
    | '/_app/admin/transactions'
    | '/_app/admin/user-portfolios'
    | '/_app/admin/users'
    | '/_app/analisis/dividend'
    | '/_app/analisis/earnings'
    | '/_app/analisis/portfolio'
    | '/_app/analisis/screener'
    | '/_app/analisis/technical'
    | '/_app/analisis/valuation'
    | '/_app/ekonomi/ai-brief'
    | '/_app/ekonomi/calendar'
    | '/_app/ekonomi/global'
    | '/_app/ekonomi/komoditas'
    | '/_app/ekonomi/macro'
    | '/_app/idx/markets'
    | '/_app/idx/screener'
    | '/_app/ekonomi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RequestAccessRoute: typeof RequestAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market-insight': {
      id: '/_app/market-insight'
      path: '/market-insight'
      fullPath: '/market-insight'
      preLoaderRoute: typeof AppMarketInsightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ekonomi': {
      id: '/_app/ekonomi'
      path: '/ekonomi'
      fullPath: '/ekonomi'
      preLoaderRoute: typeof AppEkonomiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analisis': {
      id: '/_app/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AppAnalisisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ekonomi/': {
      id: '/_app/ekonomi/'
      path: '/'
      fullPath: '/ekonomi/'
      preLoaderRoute: typeof AppEkonomiIndexRouteImport
      parentRoute: typeof AppEkonomiRoute
    }
    '/_app/idx/screener': {
      id: '/_app/idx/screener'
      path: '/idx/screener'
      fullPath: '/idx/screener'
      preLoaderRoute: typeof AppIdxScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/idx/markets': {
      id: '/_app/idx/markets'
      path: '/idx/markets'
      fullPath: '/idx/markets'
      preLoaderRoute: typeof AppIdxMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ekonomi/macro': {
      id: '/_app/ekonomi/macro'
      path: '/macro'
      fullPath: '/ekonomi/macro'
      preLoaderRoute: typeof AppEkonomiMacroRouteImport
      parentRoute: typeof AppEkonomiRoute
    }
    '/_app/ekonomi/komoditas': {
      id: '/_app/ekonomi/komoditas'
      path: '/komoditas'
      fullPath: '/ekonomi/komoditas'
      preLoaderRoute: typeof AppEkonomiKomoditasRouteImport
      parentRoute: typeof AppEkonomiRoute
    }
    '/_app/ekonomi/global': {
      id: '/_app/ekonomi/global'
      path: '/global'
      fullPath: '/ekonomi/global'
      preLoaderRoute: typeof AppEkonomiGlobalRouteImport
      parentRoute: typeof AppEkonomiRoute
    }
    '/_app/ekonomi/calendar': {
      id: '/_app/ekonomi/calendar'
      path: '/calendar'
      fullPath: '/ekonomi/calendar'
      preLoaderRoute: typeof AppEkonomiCalendarRouteImport
      parentRoute: typeof AppEkonomiRoute
    }
    '/_app/ekonomi/ai-brief': {
      id: '/_app/ekonomi/ai-brief'
      path: '/ai-brief'
      fullPath: '/ekonomi/ai-brief'
      preLoaderRoute: typeof AppEkonomiAiBriefRouteImport
      parentRoute: typeof AppEkonomiRoute
    }
    '/_app/analisis/valuation': {
      id: '/_app/analisis/valuation'
      path: '/valuation'
      fullPath: '/analisis/valuation'
      preLoaderRoute: typeof AppAnalisisValuationRouteImport
      parentRoute: typeof AppAnalisisRoute
    }
    '/_app/analisis/technical': {
      id: '/_app/analisis/technical'
      path: '/technical'
      fullPath: '/analisis/technical'
      preLoaderRoute: typeof AppAnalisisTechnicalRouteImport
      parentRoute: typeof AppAnalisisRoute
    }
    '/_app/analisis/screener': {
      id: '/_app/analisis/screener'
      path: '/screener'
      fullPath: '/analisis/screener'
      preLoaderRoute: typeof AppAnalisisScreenerRouteImport
      parentRoute: typeof AppAnalisisRoute
    }
    '/_app/analisis/portfolio': {
      id: '/_app/analisis/portfolio'
      path: '/portfolio'
      fullPath: '/analisis/portfolio'
      preLoaderRoute: typeof AppAnalisisPortfolioRouteImport
      parentRoute: typeof AppAnalisisRoute
    }
    '/_app/analisis/earnings': {
      id: '/_app/analisis/earnings'
      path: '/earnings'
      fullPath: '/analisis/earnings'
      preLoaderRoute: typeof AppAnalisisEarningsRouteImport
      parentRoute: typeof AppAnalisisRoute
    }
    '/_app/analisis/dividend': {
      id: '/_app/analisis/dividend'
      path: '/dividend'
      fullPath: '/analisis/dividend'
      preLoaderRoute: typeof AppAnalisisDividendRouteImport
      parentRoute: typeof AppAnalisisRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/user-portfolios': {
      id: '/_app/admin/user-portfolios'
      path: '/user-portfolios'
      fullPath: '/admin/user-portfolios'
      preLoaderRoute: typeof AppAdminUserPortfoliosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/transactions': {
      id: '/_app/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AppAdminTransactionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/security': {
      id: '/_app/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/prices': {
      id: '/_app/admin/prices'
      path: '/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AppAdminPricesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/insight-ai': {
      id: '/_app/admin/insight-ai'
      path: '/insight-ai'
      fullPath: '/admin/insight-ai'
      preLoaderRoute: typeof AppAdminInsightAiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/insight': {
      id: '/_app/admin/insight'
      path: '/insight'
      fullPath: '/admin/insight'
      preLoaderRoute: typeof AppAdminInsightRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/holdings': {
      id: '/_app/admin/holdings'
      path: '/holdings'
      fullPath: '/admin/holdings'
      preLoaderRoute: typeof AppAdminHoldingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/broadcast': {
      id: '/_app/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AppAdminBroadcastRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBroadcastRoute: typeof AppAdminBroadcastRoute
  AppAdminHoldingsRoute: typeof AppAdminHoldingsRoute
  AppAdminInsightRoute: typeof AppAdminInsightRoute
  AppAdminInsightAiRoute: typeof AppAdminInsightAiRoute
  AppAdminPricesRoute: typeof AppAdminPricesRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminTransactionsRoute: typeof AppAdminTransactionsRoute
  AppAdminUserPortfoliosRoute: typeof AppAdminUserPortfoliosRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBroadcastRoute: AppAdminBroadcastRoute,
  AppAdminHoldingsRoute: AppAdminHoldingsRoute,
  AppAdminInsightRoute: AppAdminInsightRoute,
  AppAdminInsightAiRoute: AppAdminInsightAiRoute,
  AppAdminPricesRoute: AppAdminPricesRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminTransactionsRoute: AppAdminTransactionsRoute,
  AppAdminUserPortfoliosRoute: AppAdminUserPortfoliosRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAnalisisRouteChildren {
  AppAnalisisDividendRoute: typeof AppAnalisisDividendRoute
  AppAnalisisEarningsRoute: typeof AppAnalisisEarningsRoute
  AppAnalisisPortfolioRoute: typeof AppAnalisisPortfolioRoute
  AppAnalisisScreenerRoute: typeof AppAnalisisScreenerRoute
  AppAnalisisTechnicalRoute: typeof AppAnalisisTechnicalRoute
  AppAnalisisValuationRoute: typeof AppAnalisisValuationRoute
}

const AppAnalisisRouteChildren: AppAnalisisRouteChildren = {
  AppAnalisisDividendRoute: AppAnalisisDividendRoute,
  AppAnalisisEarningsRoute: AppAnalisisEarningsRoute,
  AppAnalisisPortfolioRoute: AppAnalisisPortfolioRoute,
  AppAnalisisScreenerRoute: AppAnalisisScreenerRoute,
  AppAnalisisTechnicalRoute: AppAnalisisTechnicalRoute,
  AppAnalisisValuationRoute: AppAnalisisValuationRoute,
}

const AppAnalisisRouteWithChildren = AppAnalisisRoute._addFileChildren(
  AppAnalisisRouteChildren,
)

interface AppEkonomiRouteChildren {
  AppEkonomiAiBriefRoute: typeof AppEkonomiAiBriefRoute
  AppEkonomiCalendarRoute: typeof AppEkonomiCalendarRoute
  AppEkonomiGlobalRoute: typeof AppEkonomiGlobalRoute
  AppEkonomiKomoditasRoute: typeof AppEkonomiKomoditasRoute
  AppEkonomiMacroRoute: typeof AppEkonomiMacroRoute
  AppEkonomiIndexRoute: typeof AppEkonomiIndexRoute
}

const AppEkonomiRouteChildren: AppEkonomiRouteChildren = {
  AppEkonomiAiBriefRoute: AppEkonomiAiBriefRoute,
  AppEkonomiCalendarRoute: AppEkonomiCalendarRoute,
  AppEkonomiGlobalRoute: AppEkonomiGlobalRoute,
  AppEkonomiKomoditasRoute: AppEkonomiKomoditasRoute,
  AppEkonomiMacroRoute: AppEkonomiMacroRoute,
  AppEkonomiIndexRoute: AppEkonomiIndexRoute,
}

const AppEkonomiRouteWithChildren = AppEkonomiRoute._addFileChildren(
  AppEkonomiRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAnalisisRoute: typeof AppAnalisisRouteWithChildren
  AppCommunityRoute: typeof AppCommunityRoute
  AppEkonomiRoute: typeof AppEkonomiRouteWithChildren
  AppMarketInsightRoute: typeof AppMarketInsightRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIdxMarketsRoute: typeof AppIdxMarketsRoute
  AppIdxScreenerRoute: typeof AppIdxScreenerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAnalisisRoute: AppAnalisisRouteWithChildren,
  AppCommunityRoute: AppCommunityRoute,
  AppEkonomiRoute: AppEkonomiRouteWithChildren,
  AppMarketInsightRoute: AppMarketInsightRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIdxMarketsRoute: AppIdxMarketsRoute,
  AppIdxScreenerRoute: AppIdxScreenerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RequestAccessRoute: RequestAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
