-- Create feature_flags table for persistent feature flag management
-- Enables DB-backed feature rollouts, A/B testing, and gradual deployments

CREATE TABLE IF NOT EXISTS feature_flags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Core feature flag definition
  key TEXT UNIQUE NOT NULL,
  enabled BOOLEAN DEFAULT false,
  description TEXT,
  
  -- Rollout strategy
  rollout_percentage INTEGER DEFAULT 0 CHECK (rollout_percentage >= 0 AND rollout_percentage <= 100),
  
  -- Role-based targeting
  target_roles TEXT[] DEFAULT NULL,
  
  -- User-specific targeting
  target_user_ids UUID[] DEFAULT NULL,
  
  -- Expiration (auto-disable after date)
  expires_at TIMESTAMP NULL,
  
  -- Audit trail
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  
  -- Indexes for queries
  CONSTRAINT feature_flags_key_unique UNIQUE (key)
);

-- Enable RLS
ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY;

-- RLS policy: Anyone can read feature flags (they're public for client-side checks)
CREATE POLICY "Enable read access for all users" ON feature_flags
  FOR SELECT USING (true);

-- RLS policy: Only admins can modify feature flags
CREATE POLICY "Enable admin write access" ON feature_flags
  FOR ALL USING (
    auth.jwt() ->> 'role' = 'authenticated' AND
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );

-- Create index for faster feature flag lookups
CREATE INDEX idx_feature_flags_key ON feature_flags(key);
CREATE INDEX idx_feature_flags_enabled ON feature_flags(enabled)
  WHERE enabled = true;

-- Insert initial feature flags
INSERT INTO feature_flags (key, enabled, description, rollout_percentage, created_at) VALUES
-- Portfolio features (enabled for 50% rollout)
('NEW_PORTFOLIO_UI', true, 'New portfolio interface with improved analytics', 50, now()),
('PORTFOLIO_V2_ANALYTICS', true, 'Portfolio analytics v2 with advanced calculations', 30, now()),

-- AI features (enabled with role targeting)
('AI_MARKET_BRIEF', true, 'Daily market brief generated by AI', 100, now()),
('AI_DCF_VALUATION', true, 'AI-powered DCF valuation analysis', 50, now()),
('AI_SENTIMENT_ANALYSIS', true, 'Sentiment analysis from news and social media', 25, now()),

-- Community features (limited rollout)
('COMMUNITY_CHAT', true, 'Real-time community chat for members', 40, now()),
('COMMUNITY_SIGNALS', false, 'Trading signals from community analysis', 0, now()),

-- Admin features (fully enabled)
('ADMIN_BULK_USER_MANAGEMENT', true, 'Bulk user management tools for admins', 100, now()),
('ADMIN_EXPORT_REPORTS', true, 'Export reports functionality for admins', 100, now()),

-- Experimental features (low rollout)
('EXPERIMENTAL_MOBILE_APP', false, 'Mobile app for iOS/Android', 0, now()),
('EXPERIMENTAL_CRYPTO_SUPPORT', false, 'Support for crypto portfolio tracking', 0, now())
ON CONFLICT (key) DO NOTHING;

-- Create audit trigger for feature flag changes
CREATE TABLE IF NOT EXISTS feature_flags_audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  flag_key TEXT NOT NULL,
  previous_state JSONB,
  new_state JSONB,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMP DEFAULT now()
);

CREATE OR REPLACE FUNCTION audit_feature_flag_changes()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO feature_flags_audit_log (flag_key, previous_state, new_state, changed_by)
  VALUES (
    NEW.key,
    to_jsonb(OLD),
    to_jsonb(NEW),
    auth.uid()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER feature_flag_audit
  AFTER UPDATE ON feature_flags
  FOR EACH ROW
  EXECUTE FUNCTION audit_feature_flag_changes();

-- Enable RLS on audit log
ALTER TABLE feature_flags_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for admins" ON feature_flags_audit_log
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid()
      AND role = 'admin'
    )
  );
